"""MathGraph: a lightweight kernel for verifiable mathematical claims."""

from mathgraph.certificates import Certificate, TerminalForm, VerificationStatus
from mathgraph.alchemy import (
    AlchemicalPhase,
    AlchemicalStatus,
    AlchemicalStep,
    AlchemicalTrace,
    make_alchemical_trace_id,
)
from mathgraph.agent_biography import (
    AgentBiography,
    AgentExperience,
    AgentExperienceOutcome,
    AgentProfile,
    AgentStatus,
    HTiltLiteScore,
    score_route_htilt_lite,
)
from mathgraph.projection import (
    ProjectionCandidate,
    ProjectionResult,
    ProjectionRuleKind,
    ProjectionStatus,
    ProjectionTrace,
    advisory_similarity_projection,
    exact_known_projection,
    make_projection_candidate_id,
    make_projection_result_id,
    make_projection_trace_id,
    projection_trace_to_agent_experiences,
    projection_trace_to_alchemical_trace,
    run_projection_engine,
    source_weakening_false_projection,
    target_strengthening_false_projection,
    transitivity_projection,
)
from mathgraph.proof_verification import (
    ProofArtifact,
    ProofArtifactKind,
    ProofVerificationResult,
    ProofVerificationStatus,
    ProofVerificationTrace,
    ProofVerifierKind,
    chain_audit_proof,
    import_verified_proof,
    make_cut_candidate,
    make_lean_skeleton,
    make_lemma_candidate,
    make_proof_artifact_id,
    make_proof_result_id,
    make_proof_trace_id,
    make_theorem_schema,
    proof_verification_trace_to_agent_experiences,
    proof_verification_trace_to_alchemical_trace,
    proof_verification_trace_to_projection_candidates,
    run_proof_verification_pipeline,
    run_proof_verifier,
)
from mathgraph.proof_digestion import (
    DigestionArtifactKind,
    DigestionStatus,
    ExpositionNote,
    KeyIdeaCandidate,
    LawbookAssimilationCandidate,
    ProofDependencyMap,
    ProofDigestionTrace,
    ProofStepDigest,
    ReusableSchemaCandidate,
    classify_proof_steps,
    digest_lean_adapter_trace,
    digest_proof_artifact,
    digest_proof_verification_trace,
    digest_verification_episode_trace,
    extract_dependencies_from_proof_artifact,
    extract_key_ideas,
    extract_reusable_schemas,
    make_assimilation_candidate_id,
    make_dependency_map_id,
    make_exposition_note,
    make_exposition_note_id,
    make_key_idea_id,
    make_lawbook_assimilation_candidate,
    make_proof_digestion_trace_id,
    make_schema_id,
    make_step_digest_id,
    proof_artifact_from_content,
    proof_digestion_trace_to_agent_experiences,
    proof_digestion_trace_to_alchemical_trace,
    proof_digestion_trace_to_continuation_outputs,
    proof_digestion_trace_to_projection_candidates,
)
from mathgraph.roadmap_alignment import (
    RoadmapAlignmentFinding,
    RoadmapAlignmentReport,
    check_roadmap_alignment,
)
from mathgraph.mathlib_local_allowlist import *
from mathgraph.mathlib_module_verification import *
from mathgraph.route_telemetry import (
    HTiltTelemetrySummary,
    RouteTelemetryEvent,
    RouteTelemetryKind,
    RouteTelemetryLedger,
    RouteTelemetryOutcome,
    build_route_telemetry_ledger,
    killing_table,
    make_route_telemetry_event_id,
    make_route_telemetry_ledger_id,
    route_outcome_table,
    summarize_h_tilt_telemetry,
    telemetry_events_from_episode,
    transition_table,
)
from mathgraph.spectral_htilt import (
    SpectralHTiltConfig,
    SpectralHTiltEstimate,
    SpectralStateEstimate,
    build_generator_K,
    build_killing_pressure_from_ledger,
    build_transition_matrix_from_ledger,
    compute_multiplicative_bridge,
    compute_survivor_distribution,
    estimate_left_support_q,
    estimate_right_survival_h,
    estimate_spectral_htilt,
    l1_error,
    multiply_matrix_vector,
    multiply_transpose_matrix_vector,
    normalize_vector,
    route_priorities_from_estimate,
)
from mathgraph.domain_claims import (
    AdvisoryOnlyAdapter,
    ClaimIRStatus,
    ClaimKind,
    ClaimParseResult,
    DomainAdapter,
    DomainClaim,
    FormalWorld as DomainFormalWorld,
    FormalWorldKind as DomainFormalWorldKind,
    FormalWorldRegistry,
    LeanSkeletonAdapter,
    MagmaEquationalAdapter,
    default_formal_world_registry,
    domain_claim_to_verification_episode_input,
    get_default_domain_adapters,
    make_domain_claim_id,
    normalize_domain_claim,
    parse_domain_claim,
    route_domain_claim_to_existing_inputs,
    run_domain_claim_pipeline,
)
from mathgraph.lean_adapter import (
    LeanAdapterTrace,
    LeanArtifactStatus,
    LeanCheckResult,
    LeanEnvironment,
    LeanFileArtifact,
    check_lean_file,
    detect_lean_environment,
    extract_lean_imports,
    extract_lean_theorem_names,
    import_checked_lean_artifact,
    lean_adapter_trace_to_agent_experiences,
    lean_adapter_trace_to_alchemical_trace,
    lean_adapter_trace_to_proof_verification_trace,
    lean_file_from_proof_artifact,
    make_lean_adapter_trace_id,
    make_lean_check_result_id,
    make_lean_file_id,
    proof_artifact_from_lean_file,
    run_lean_adapter_pipeline,
)
from mathgraph.continuation_actions import (
    ContinuationAction,
    ContinuationActionInput,
    ContinuationActionKind,
    ContinuationActionOutput,
    ContinuationActionRegistry,
    ContinuationActionStatus,
    ContinuationActionTrace,
    ContinuationOutputKind,
    apply_continuation_action,
    continuation_outputs_to_episode_inputs,
    continuation_outputs_to_projection_candidates,
    continuation_outputs_to_proof_artifacts,
    continuation_trace_to_agent_experiences,
    continuation_trace_to_alchemical_trace,
    default_continuation_action_registry,
    drop_variable_from_expr,
    dualize_magma_expression,
    form_equivalence_claim,
    form_implication_claim,
    identify_variables_in_expr,
    make_continuation_action_id,
    make_continuation_input_id,
    make_continuation_output_id,
    make_continuation_registry_id,
    make_continuation_trace_id,
    negate_target_task,
    run_continuation_actions,
)
from mathgraph.continuation_curriculum import (
    ContinuationCurriculum,
    CurriculumBuildStrategy,
    CurriculumStage,
    CurriculumStageKind,
    CurriculumStageStatus,
    CurriculumTraceStatus,
    build_continuation_curriculum,
    build_curriculum_from_actions,
    build_curriculum_from_proof_digestion,
    build_curriculum_from_projection_candidates,
    build_curriculum_from_repair_loop,
    build_curriculum_from_verifier_feedback,
    build_empty_curriculum,
    build_magma_equational_curriculum,
    curriculum_to_agent_experiences,
    curriculum_to_alchemical_trace,
    curriculum_to_continuation_outputs,
    curriculum_to_episode_inputs,
    curriculum_to_projection_candidates,
    curriculum_to_route_telemetry_events,
    make_curriculum_id,
    make_curriculum_stage_id,
    normalize_curriculum_target,
)
from mathgraph.discovery_value import (
    DiscoveryValueDecision,
    DiscoveryValueObjectKind,
    DiscoveryValueReport,
    DiscoveryValueScore,
    DiscoveryValueSignal,
    DiscoveryValueSignalKind,
    DiscoveryValueStatus,
    build_discovery_value_report,
    discovery_value_report_to_agent_experiences,
    discovery_value_report_to_alchemical_trace,
    discovery_value_report_to_continuation_outputs,
    discovery_value_report_to_curriculum,
    discovery_value_report_to_route_telemetry_events,
    make_discovery_value_report_id,
    make_discovery_value_score_id,
    make_discovery_value_signal_id,
    score_agent_experience,
    score_alchemical_trace,
    score_continuation_output,
    score_curriculum,
    score_curriculum_stage,
    score_lawbook_assimilation_candidate,
    score_object,
    score_projection_candidate,
    score_proof_digestion_trace,
    score_repair_plan,
    score_repair_loop,
    score_route_telemetry_event,
    score_verifier_feedback,
)
from mathgraph.verifier_feedback import (
    FlawSeverity,
    RepairActionKind,
    RepairLoopStatus,
    RepairLoopTrace,
    RepairPlan,
    VerifierFeedback,
    VerifierFeedbackStatus,
    classify_flaw_from_message,
    feedback_from_lean_adapter_trace,
    feedback_from_proof_verification_result,
    feedback_from_proof_verification_trace,
    feedback_from_text,
    feedback_from_verification_episode_trace,
    make_repair_loop_trace_id,
    make_repair_plan_id,
    make_verifier_feedback_id,
    plan_repair_from_feedback,
    repair_loop_trace_to_agent_experiences,
    repair_loop_trace_to_alchemical_trace,
    repair_loop_trace_to_continuation_outputs,
    repair_loop_trace_to_projection_candidates,
    repair_loop_trace_to_route_telemetry_events,
    run_repair_loop,
)
from mathgraph.root_constructors import (
    ConstructorAttempt,
    ConstructorPlan as RootAwareConstructorPlan,
    RootConstructorKind,
    RootConstructorStatus,
    RootConstructorTrace,
    RootSignal,
    compile_constructor_plans as compile_root_constructor_plans,
    load_constructor_plans_jsonl,
    load_root_signals_json,
    load_root_signals_jsonl,
    make_constructor_attempt_id,
    make_constructor_plan_id,
    make_root_constructor_trace_id,
    make_root_signal_id,
    root_constructor_trace_to_agent_experiences,
    root_constructor_trace_to_alchemical_trace,
    root_constructor_trace_to_projection_candidates,
    run_constructor_attempts,
    run_root_aware_constructors,
)
from mathgraph.verification_episode import (
    VerificationEpisodeInput,
    VerificationEpisodeRouteDecision,
    VerificationEpisodeStatus,
    VerificationEpisodeTrace,
    VerificationRouteKind,
    choose_episode_routes,
    combine_episode_alchemical_trace,
    make_verification_episode_id,
    run_verification_episode,
)
from mathgraph.claims import GeneralClaim
from mathgraph.certificate_assimilation import (
    CertificateAssimilationConfig,
    CertificateAssimilationResult,
    CertificateAssimilationSummary,
    run_certificate_assimilation,
)
from mathgraph.asset_discovery import (
    AssetDiscoveryConfig,
    AssetDiscoveryResult,
    discover_mathgraph_assets,
)
from mathgraph.asset_materialization import (
    AssetMaterializationConfig,
    AssetMaterializationResult,
    materialize_mathgraph_assets,
)
from mathgraph.artifact_warehouse import (
    import_closure_oracle_csv,
    import_table_registry_csv,
    import_v16_6_2_elevated_false_dir,
    import_v16_7_root_atlas_dir,
    register_external_theory_kernel,
    register_domain_kernel_in_store,
    register_etp_kernel,
)
from mathgraph.chewing_smoke import (
    ChewingSmokeConfig,
    ChewingSmokeResult,
    ChewingSmokeStageResult,
    run_chewing_smoke,
)
from mathgraph.countermodel_importer import (
    CountermodelImportConfig,
    CountermodelImportResult,
    CountermodelImportRunResult,
    import_finite_countermodel_results,
)
from mathgraph.corpus import CertificateCorpus
from mathgraph.client import (
    MathGraphAnswer,
    MathGraphAuditError,
    MathGraphClient,
    MathGraphClientConfig,
)
from mathgraph.equations import Equation, parse_equation
from mathgraph.episode_learning import (
    AssimilationLearningRecord,
    ConstructorYieldStats,
    EpisodeLearningConfig,
    EpisodeLearningResult,
    ResidualBasinStats,
    RouteYieldStats,
    learn_from_assimilation_episodes,
)
from mathgraph.derived_certificates import (
    DerivedCertificate,
    DerivedCertificateGenerator,
    DerivedCertificateStats,
)
from mathgraph.domain_kernels import (
    DomainKernel,
    HostVerifier,
    ImportedTheoryObject,
    ImportedTheoryRelation,
    SemanticEmbedding as DomainKernelSemanticEmbedding,
    SemanticEmbeddingKind,
    TheoryObjectKind as ImportedTheoryObjectKind,
    TheoryRelationKind,
    make_external_theory_domain_kernel,
    make_etp_domain_kernel,
)
from mathgraph.denotation import (
    DenotationRecord,
    DenotationStatus,
    can_promote_denotation,
    require_denotes,
)
from mathgraph.formal_worlds import (
    FormalWorld,
    FormalWorldKind,
    external_theory_formal_world_precedent,
    etp_magma_formal_world,
)
from mathgraph.language_fragments import (
    LanguageFragment,
    external_theory_precedent_fragment,
    etp_magma_equations_fragment,
)
from mathgraph.paradox_guards import (
    GuardSeverity,
    ParadoxGuard,
    ParadoxGuardKind,
    ParadoxGuardResult,
    semantic_embedding_artifact_guard,
    set_collapse_guard,
)
from mathgraph.predication import (
    PredicateKind,
    PredicationFact,
    PredicationMode,
    encodes,
    exemplifies,
)
from mathgraph.reason_containment import ContainmentMode, ReasonContainmentRecord
from mathgraph.semantic_embeddings import (
    ArtifactRisk,
    EmbeddingKind,
    ProofTransportStatus,
    SemanticEmbedding,
)
from mathgraph.theory_objectification import (
    AnalyticTruth,
    TheoryDenotation,
    TheoryObjectKind,
    TheoryObjectificationMap,
    TheoryReading,
)
from mathgraph.object_language import (
    FormulaRole,
    ObjectLanguageFormula,
    ObjectLanguageKind,
    ObjectLanguageTerm,
    normalize_object_language_text,
)
from mathgraph.theory_registry import (
    InferenceRule,
    ProofMethod,
    ProofMethodKind,
    TheoryDeclaration,
    TheoryDeclarationKind,
)
from mathgraph.isabelle_exports import (
    HostObjectTheoremLink,
    IsabelleExportRecord,
    IsabelleExportStatus,
)
from mathgraph.logical_workbench import (
    LogicWorkbench,
    WorkbenchLayer,
    WorkbenchLifecycleStatus,
    reference_logic_workbench,
    mathgraph_default_workbench,
)
from mathgraph.local_service import (
    MathGraphHTTPServer,
    MathGraphRequestHandler,
    make_server,
)
from mathgraph.embedding_strategies import (
    AutomationBias,
    EmbeddingStrategy,
    EmbeddingStrategyProfile,
    SemanticsRepresentation,
    SyntaxRepresentation,
)
from mathgraph.faithfulness import (
    CompletenessStatus,
    FaithfulnessAssessment,
    FaithfulnessStatus,
    SoundnessStatus,
)
from mathgraph.logic_combinations import CombinationMethod, ConflictPolicy, LogicCombination
from mathgraph.verifier_backends import (
    BackendRole,
    VerifierBackendKind,
    VerifierBackendProfile,
    isabelle_nitpick_backend_placeholder,
    isabelle_nunchaku_backend_placeholder,
    isabelle_sledgehammer_backend_placeholder,
    lean_backend_placeholder,
    python_finite_table_checker_backend,
)
from mathgraph.backend_results import (
    ModelFinderResult,
    ModelFinderStatus,
    ProofFinderResult,
    ProofFinderStatus,
)
from mathgraph.benchmarking import (
    BenchmarkCase,
    BenchmarkExpectedStatus,
    BenchmarkObservedStatus,
    BenchmarkResult,
    BenchmarkRun,
    BenchmarkSuite,
    etp_matrix_benchmark_suite_metadata,
    reference_methodology_benchmark_suite_metadata,
)
from mathgraph.correspondence import (
    CorrespondenceClaim,
    CorrespondenceDirection,
    CorrespondenceStatus,
)
from mathgraph.interpretation_choice import ChoicePointStatus, InterpretationChoicePoint
from mathgraph.workbench_presets import (
    build_reference_logic_workbench_bundle,
    build_mathgraph_etp_workbench_bundle,
)
from mathgraph.proof_motifs import (
    ProofMotif,
    ProofMotifKind,
    ProofRouteStatus,
    infer_proof_motif_kind,
    make_proof_motif_id,
)
from mathgraph.lemma_candidates import (
    CutIntroductionKind,
    LemmaCandidate,
    LemmaCandidateStatus,
    canonical_lemma_name,
    make_lemma_candidate_id,
)
from mathgraph.lean_artifacts import (
    LeanArtifact,
    LeanArtifactKind,
    LeanVerificationStatus,
    render_lean_skeleton,
)
from mathgraph.proof_atlas import ProofAtlas, build_proof_atlas_from_true_rows
from mathgraph.proof_importers import (
    discover_true_proof_artifacts,
    import_true_proof_artifacts_to_store,
    load_true_proof_rows,
    normalize_true_proof_row,
)
from mathgraph.metabolic_cycle import (
    MetabolicCycleConfig,
    MetabolicCycleResult,
    MetabolicCycleStageResult,
    run_metabolic_cycle,
)
from mathgraph.m0_certificate_factory import (
    M0EpisodeConfig,
    M0EpisodeMetrics,
    M0EpisodeResult,
    M0PairResult,
    run_m0_episode,
)
from mathgraph.m0_audit import AuditFinding, AuditReport, audit_m0_store
from mathgraph.terminal_contract import (
    TerminalContractResult,
    VerifierBoundary,
)
from mathgraph.metabolic_diagnostics import (
    MetabolicDiagnostics,
    compute_derived_amplification_factor,
    compute_residual_compression_gain,
    evaluate_better_shaped_unknown,
)
from mathgraph.synthetic_cycle_data import build_synthetic_metabolic_frontier
from mathgraph.types import (
    ExtensionalCollapsePolicy,
    HyperintensionalIdentityMode,
    MathGraphType,
    ObjectIdentityMode,
    TypeParseError,
    TypedObject,
    UniquenessStatus,
    canonical_encoded_object_id,
    normalize_type_expr,
    parse_type_expr,
    should_merge_objects,
)
from mathgraph.artifact_importers import (
    load_v1662_elevated_false_certificates,
    load_v167_obstructions,
    load_v167_reason_nodes,
    load_v167_root_nodes,
)
from mathgraph.hashing import (
    canonical_json,
    content_id,
    hash_certificate,
    hash_file,
    hash_trace,
    sha256_hex,
    sha256_json,
    sha256_text,
)
from mathgraph.flywheel import (
    FlywheelConfig,
    FlywheelResult,
    FlywheelStageResult,
    run_mathgraph_flywheel,
)
from mathgraph.frontier_builder import (
    FrontierBuilderConfig,
    FrontierBuilderResult,
    FrontierCandidate,
    KnownPairFilter,
    build_candidate_frontier,
)
from mathgraph.finite_countermodel_executor import (
    FiniteCountermodelConfig,
    FiniteCountermodelResult,
    FiniteCountermodelRunResult,
    run_finite_countermodel_tasks,
)
from mathgraph.htilt_scheduler import (
    HTiltScheduler,
    HTiltSchedulerStats,
    HTiltScoreBreakdown,
    ScheduledTask,
    SchedulerInputPair,
)
from mathgraph.kernel import Kernel
from mathgraph.kernel_oracle import KernelOracle, OracleAnswer
from mathgraph.lawbook import (
    CertificateLawbook,
    LawbookAcceptanceBoundary,
    LawbookEntry,
    LawbookEntryKind,
    LawbookEntryStatus,
    LawbookReview,
    LawbookReviewDecision,
    LawbookStore as AcceptedLawbookStore,
    LawbookStoreStatus,
    accept_lawbook_entry,
    audit_lawbook_entry,
    audit_lawbook_store,
    build_lawbook_store,
    lawbook_entry_from_assimilation_candidate,
    lawbook_entry_from_certificate_like,
    lawbook_entry_from_discovery_value_score,
    lawbook_entry_from_projection_candidate,
    lawbook_entry_from_proof_digestion,
    lawbook_store_to_agent_experiences,
    lawbook_store_to_alchemical_trace,
    lawbook_store_to_continuation_outputs,
    lawbook_store_to_projection_candidates,
    lawbook_store_to_route_telemetry_events,
    make_lawbook_entry_id,
    make_lawbook_review_id,
    make_lawbook_store_id,
    review_lawbook_candidate,
)
from mathgraph.lawbook_query import (
    KnownSkipDecision,
    LawbookQuery,
    LawbookQueryAnswer,
    LawbookQueryKind,
    LawbookQueryReport,
    LawbookQueryReportStatus,
    LawbookQueryStatus,
    LawbookTrustLevel,
    build_lawbook_trust_summary,
    explain_lawbook_answer,
    known_skip_for_claim,
    lawbook_query_answer_to_continuation_outputs,
    lawbook_query_answer_to_projection_candidates,
    lawbook_query_report_to_agent_experiences,
    lawbook_query_report_to_alchemical_trace,
    lawbook_query_report_to_route_telemetry_events,
    make_certificate_query,
    make_claim_query,
    make_entry_query,
    make_known_skip_query,
    make_lawbook_query_answer_id,
    make_lawbook_query_id,
    make_lawbook_query_report_id,
    make_trust_summary_query,
    query_lawbook_store,
    query_lawbook_store_by_certificate,
    query_lawbook_store_by_claim,
    query_lawbook_store_by_entry,
    query_lawbook_store_many,
)
from mathgraph.structural_identity import (
    StructuralEdge,
    StructuralEdgeKind,
    StructuralGraph,
    StructuralIdentityReport,
    StructuralIdentityReportStatus,
    StructuralMatchKind,
    StructuralMergeCandidate,
    StructuralMergeDecision,
    StructuralNode,
    StructuralNodeKind,
    StructuralObjectKind,
    StructuralSignature,
    audit_structural_identity_report,
    audit_structural_merge_candidate,
    build_structural_identity_report,
    compare_structural_signatures,
    compute_structural_signature,
    find_structural_merge_candidates,
    make_structural_edge_id,
    make_structural_graph_id,
    make_structural_identity_report_id,
    make_structural_merge_candidate_id,
    make_structural_node_id,
    make_structural_signature_id,
    structural_graph_from_agent_experience,
    structural_graph_from_alchemical_trace,
    structural_graph_from_curriculum,
    structural_graph_from_curriculum_stage,
    structural_graph_from_discovery_value_score,
    structural_graph_from_lawbook_entry,
    structural_graph_from_lawbook_query_answer,
    structural_graph_from_lawbook_store,
    structural_graph_from_mapping,
    structural_graph_from_object,
    structural_graph_from_projection_candidate,
    structural_graph_from_proof_digestion_trace,
    structural_graph_from_repair_loop,
    structural_graph_from_verifier_feedback,
    structural_identity_report_to_agent_experiences,
    structural_identity_report_to_alchemical_trace,
    structural_identity_report_to_continuation_outputs,
    structural_identity_report_to_curriculum,
    structural_identity_report_to_lawbook_candidates,
    structural_identity_report_to_route_telemetry_events,
)
from mathgraph.habit_rules import (
    HabitCandidate, HabitFormationReport, HabitFormationReportStatus, HabitObservation,
    HabitObservationKind, HabitOutcome, HabitReview, HabitReviewDecision, HabitRule,
    HabitRuleKind, HabitStatus, HabitStore, apply_habit_rules, audit_habit_candidate,
    audit_habit_report, audit_habit_rule, build_habit_candidates,
    build_habit_formation_report, build_habit_store, habit_observations_from_object,
    habit_report_to_agent_experiences, habit_report_to_alchemical_trace,
    habit_report_to_continuation_outputs, habit_report_to_curriculum,
    habit_report_to_discovery_value_scores, habit_report_to_lawbook_candidates,
    habit_report_to_route_telemetry_events, infer_condition_key, infer_rule_kind,
    make_habit_candidate_id, make_habit_formation_report_id, make_habit_observation_id,
    make_habit_review_id, make_habit_rule_id, make_habit_store_id,
    promote_habit_candidate, rank_routes_with_habits, review_habit_candidate,
)
from mathgraph.reason_compression import (
    ReasonAtomKind,ReasonCandidate,ReasonCandidateKind,ReasonCompressionReport,
    ReasonCompressionReportStatus,ReasonNode,ReasonObservation,ReasonObservationKind,
    ReasonReview,ReasonReviewDecision,ReasonStatus,apply_reason_nodes,audit_reason_candidate,
    audit_reason_node,audit_reason_report,build_reason_candidates,build_reason_compression_report,
    check_reason_minimality,classify_atom_kind,extract_atoms_from_mapping,
    make_reason_candidate_id,make_reason_compression_report_id,make_reason_node_id,
    make_reason_observation_id,make_reason_review_id,normalize_reason_atom,
    promote_reason_candidate,rank_routes_with_reasons,reason_observations_from_object,
    reason_report_to_agent_experiences,reason_report_to_alchemical_trace,
    reason_report_to_continuation_outputs,reason_report_to_curriculum,
    reason_report_to_discovery_value_scores,reason_report_to_lawbook_candidates,
    reason_report_to_route_telemetry_events,reason_report_to_structural_identity_objects,
    review_reason_candidate,
)
from mathgraph.process_memory import (
    ProcessContextItem, ProcessContextKind, ProcessContextRole, ProcessElimination,
    ProcessEliminationKind, ProcessEpisodeRecord, ProcessEpisodeStatus,
    ProcessMemoryAnswer, ProcessMemoryAnswerStatus, ProcessMemoryQuery,
    ProcessMemoryQueryKind, ProcessMemoryReport, ProcessMemoryReportStatus,
    ProcessMemoryStore, ProcessTransition, ProcessTransitionKind,
    audit_process_context_item, audit_process_episode_record,
    audit_process_memory_answer, audit_process_memory_report,
    build_process_memory_store, explain_process_memory_answer,
    make_process_context_id, make_process_elimination_id, make_process_episode_id,
    make_process_memory_answer_id, make_process_memory_query_id,
    make_process_memory_report_id, make_process_memory_store_id,
    make_process_query_by_agent, make_process_query_by_certificate,
    make_process_query_by_claim, make_process_query_by_episode,
    make_process_query_by_habit_rule, make_process_query_by_lawbook_entry,
    make_process_query_by_reason_node, make_process_query_by_route,
    make_process_text_query, make_process_transition_id,
    make_process_trust_summary_query, process_episode_from_object,
    process_report_to_agent_experiences, process_report_to_alchemical_trace,
    process_report_to_continuation_outputs, process_report_to_curriculum,
    process_report_to_discovery_value_scores, process_report_to_habit_observations,
    process_report_to_lawbook_candidates, process_report_to_reason_observations,
    process_report_to_route_telemetry_events, process_report_to_structural_identity_objects,
    query_process_memory_store, query_process_memory_store_many,
    summarize_eliminations, summarize_route_processes, trace_episode_lineage,
)
from mathgraph.structure_registry import (
    ProjectionCompatibility, StructureDescriptor, StructureFamily,
    StructureFeatureKind, StructureMapping, StructureObjectKind,
    StructureRegistryEntry, StructureRegistryReport, StructureRegistryReportStatus,
    StructureRegistryStore, StructureType, TypedProjectionCandidate,
    TypedProjectionStatus, audit_structure_descriptor, audit_structure_mapping,
    audit_structure_registry_report, audit_typed_projection_candidate,
    build_structure_mappings, build_structure_registry_report,
    build_structure_registry_store, build_typed_projection_candidates,
    classify_structure_feature, compute_structure_mapping, default_structure_types,
    extract_structure_features_from_mapping, infer_structure_families,
    make_structure_descriptor_id, make_structure_mapping_id,
    make_structure_registry_entry_id, make_structure_registry_report_id,
    make_structure_registry_store_id, make_structure_type_id,
    make_typed_projection_candidate_id, normalize_structure_atom,
    structure_descriptors_from_object, structure_report_to_agent_experiences,
    structure_report_to_alchemical_trace, structure_report_to_continuation_outputs,
    structure_report_to_curriculum, structure_report_to_discovery_value_scores,
    structure_report_to_habit_observations, structure_report_to_lawbook_candidates,
    structure_report_to_process_episodes, structure_report_to_projection_candidates,
    structure_report_to_reason_observations, structure_report_to_route_telemetry_events,
    structure_report_to_structural_identity_objects,
    typed_projection_candidate_from_mapping,
)
from mathgraph.role_objects import (
    RoleCandidateStatus, RoleConditionKind, RoleConjectureCandidate,
    RoleConjectureKind, RoleDefinitionCandidate, RoleObject, RoleObjectKind,
    RoleObjectReport, RoleObjectReportStatus, RoleReview, RoleReviewDecision,
    RoleSignature, RoleSourceKind, RoleWitnessCandidate, RoleWitnessStatus,
    apply_role_objects_to_routes, audit_role_conjecture_candidate,
    audit_role_definition_candidate, audit_role_object, audit_role_object_report,
    audit_role_signature, audit_role_witness_candidate,
    build_role_conjecture_candidates, build_role_definition_candidates,
    build_role_object_report, build_role_witness_candidates,
    classify_role_condition, extract_role_conditions_from_mapping,
    infer_role_kind, make_role_conjecture_candidate_id,
    make_role_definition_candidate_id, make_role_object_id,
    make_role_object_report_id, make_role_review_id, make_role_signature_id,
    make_role_witness_candidate_id, normalize_role_atom, promote_role_definition_candidate,
    propose_role_name, rank_routes_with_role_objects, review_role_definition_candidate,
    role_report_to_agent_experiences, role_report_to_alchemical_trace,
    role_report_to_continuation_outputs, role_report_to_curriculum,
    role_report_to_discovery_value_scores, role_report_to_habit_observations,
    role_report_to_lawbook_candidates, role_report_to_process_episodes,
    role_report_to_reason_observations, role_report_to_route_telemetry_events,
    role_report_to_structure_descriptors, role_report_to_structural_identity_objects,
    role_report_to_typed_projection_candidates, role_signatures_from_object,
)
from mathgraph.structural_analogy import (
    AnalogyBreak, AnalogyBreakKind, AnalogyCandidateStatus, AnalogyFeatureKind,
    AnalogyFeatureMap, AnalogyRelationKind, AnalogyReview, AnalogyReviewDecision,
    AnalogySource, AnalogySourceKind, ExpositionNote as AnalogyExpositionNote,
    ExpositionNoteKind, StructuralAnalogyCandidate, StructuralAnalogyReport,
    StructuralAnalogyReportStatus, analogy_report_to_agent_experiences,
    analogy_report_to_alchemical_trace, analogy_report_to_continuation_outputs,
    analogy_report_to_curriculum, analogy_report_to_discovery_value_scores,
    analogy_report_to_habit_observations, analogy_report_to_lawbook_candidates,
    analogy_report_to_process_episodes, analogy_report_to_reason_observations,
    analogy_report_to_role_signatures, analogy_report_to_route_telemetry_events,
    analogy_report_to_structural_identity_objects, analogy_report_to_structure_descriptors,
    analogy_report_to_typed_projection_candidates, analogy_sources_from_object,
    apply_analogy_candidates_to_routes, audit_analogy_break, audit_analogy_feature_map,
    audit_analogy_source, audit_exposition_note, audit_structural_analogy_candidate,
    audit_structural_analogy_report, build_analogy_feature_maps,
    build_structural_analogy_candidates, build_structural_analogy_report,
    classify_analogy_feature, compute_analogy_feature_map,
    exposition_notes_from_candidate, extract_analogy_features_from_mapping,
    identify_analogy_breaks, infer_analogy_relation_kind, make_analogy_break_id,
    make_analogy_feature_map_id, make_analogy_review_id, make_analogy_source_id,
    make_exposition_note_id as make_analogy_exposition_note_id,
    make_structural_analogy_candidate_id, make_structural_analogy_report_id,
    normalize_analogy_atom, rank_routes_with_analogies,
    review_structural_analogy_candidate, structural_analogy_candidate_from_map,
)
from mathgraph.formal_world_adapters import (
    AdapterOperation, AdapterSupportLevel, FormalWorldAdapterCapability,
    FormalWorldAdapterReport, FormalWorldAdapterReportStatus, FormalWorldAdapterSpec,
    FormalWorldHandoff, FormalWorldKind as AdapterFormalWorldKind,
    FormalWorldNormalizeResult, FormalWorldParseResult, FormalWorldTask,
    FormalWorldTaskKind, FormalWorldValidationResult, HandoffKind, HandoffStatus,
    NormalizeStatus, ParseStatus, ValidationStatus, adapter_report_to_agent_experiences,
    adapter_report_to_alchemical_trace, adapter_report_to_analogy_sources,
    adapter_report_to_continuation_outputs, adapter_report_to_curriculum,
    adapter_report_to_discovery_value_scores, adapter_report_to_habit_observations,
    adapter_report_to_lawbook_candidates, adapter_report_to_process_episodes,
    adapter_report_to_reason_observations, adapter_report_to_role_signatures,
    adapter_report_to_route_telemetry_events, adapter_report_to_structural_identity_objects,
    adapter_report_to_structure_descriptors, adapter_report_to_typed_projection_candidates,
    adapter_spec_for_world, audit_adapter_capability, audit_adapter_spec,
    audit_formal_world_adapter_report, audit_formal_world_handoff,
    audit_formal_world_task, audit_normalize_result, audit_parse_result,
    audit_validation_result, build_formal_world_adapter_report,
    default_formal_world_adapter_capabilities, default_formal_world_adapter_specs,
    detect_formal_world_kind, formal_world_inputs_from_object, handoffs_from_tasks,
    make_adapter_capability_id, make_adapter_spec_id, make_formal_world_adapter_report_id,
    make_formal_world_handoff_id, make_formal_world_normalize_id, make_formal_world_parse_id,
    make_formal_world_task_id, make_formal_world_validation_id,
    normalize_finite_structure_parse, normalize_formal_world_parse,
    normalize_generic_formal_parse, normalize_lean_like_parse, normalize_magma_equational_parse,
    normalize_proof_text_parse, parse_finite_structure, parse_formal_world_input,
    parse_generic_formal, parse_lean_like, parse_magma_equational, parse_proof_text,
    tasks_from_validation, validate_formal_world_normalization,
)
from mathgraph.proof_system_integration import (
    CheckCommandKind, CheckRequestStatus, CheckResultStatus, ImportEdgeKind,
    ProofArtifactKind as ProofSystemArtifactKind, ProofArtifactManifest,
    ProofArtifactStatus as ProofSystemArtifactStatus, ProofBoundaryEvidence,
    ProofBoundaryKind, ProofCheckCommandContract, ProofCheckRequest,
    ProofCheckResult, ProofImportGraph, ProofProjectManifest, ProofSystemIntegrationReport,
    ProofSystemIntegrationReportStatus, ProofSystemKind, ProofSystemSpec,
    ProofSystemTask, ProofSystemTaskKind, TrustedImportStatus, TrustedProofImportRecord,
    audit_proof_artifact_manifest, audit_proof_boundary_evidence,
    audit_proof_check_command_contract, audit_proof_check_request,
    audit_proof_check_result, audit_proof_import_graph, audit_proof_project_manifest,
    audit_proof_system_integration_report, audit_proof_system_spec, audit_proof_system_task,
    audit_trusted_proof_import_record, build_proof_import_graph,
    build_proof_project_manifest, build_proof_system_integration_report,
    create_check_request, default_check_command_contract_for_artifact,
    default_proof_system_specs, detect_proof_system_kind, extract_coq_imports,
    extract_coq_theorem_names, extract_generic_proof_markers, extract_isabelle_imports,
    extract_isabelle_theorem_names, proof_artifact_manifest_from_path,
    proof_artifact_manifest_from_text, proof_boundary_evidence_from_check_result,
    proof_boundary_evidence_from_trusted_import, proof_system_inputs_from_object,
    proof_system_report_to_agent_experiences, proof_system_report_to_alchemical_trace,
    proof_system_report_to_analogy_sources, proof_system_report_to_continuation_outputs,
    proof_system_report_to_curriculum, proof_system_report_to_discovery_value_scores,
    proof_system_report_to_habit_observations, proof_system_report_to_lawbook_candidates,
    proof_system_report_to_process_episodes, proof_system_report_to_proof_digestion_inputs,
    proof_system_report_to_reason_observations, proof_system_report_to_repair_traces,
    proof_system_report_to_role_signatures, proof_system_report_to_route_telemetry_events,
    proof_system_report_to_structural_identity_objects, proof_system_report_to_structure_descriptors,
    proof_system_report_to_typed_projection_candidates, proof_system_report_to_verifier_feedback,
    proof_system_spec_for_kind, proof_system_tasks_from_artifacts,
    proof_system_tasks_from_check_results, proof_system_tasks_from_trusted_imports,
    trusted_import_record_from_mapping,
)
from mathgraph.semantic_intake import *
from mathgraph.api_service import *
from mathgraph.existential_agents import *
from mathgraph.hardening import *
from mathgraph.verifier_execution import *
from mathgraph.verifier_fixtures import *
from mathgraph.verified_corpus import *
from mathgraph.lean_project_subset import *
from mathgraph.mathlib_micro_subset import *
from mathgraph.e2e_testdrive import *
from mathgraph.lawbook_store import LawbookStore, LawbookStoreStats
from mathgraph.ledger import JsonlLedger
from mathgraph.outcome_dataset import (
    CompoundingDiagnostics,
    OutcomeDatasetBuilder,
    OutcomeDatasetStats,
    PairOutcome,
    extract_pair_features as extract_outcome_pair_features,
)
from mathgraph.obstruction_atlas import ConstructorPressure, ObstructionNode
from mathgraph.pair_advisor import PairAdvice, advise_many, advise_pair, extract_pair_features
from mathgraph.reason_nodes import ReasonNode
from mathgraph.refutations import RefutationCertificate
from mathgraph.root_consolidation import consolidate_root_nodes
from mathgraph.root_nodes import (
    RootAlias,
    RootCertificateCoverage,
    RootNode,
    RootObstructionLink,
    RootReasonLink,
)
from mathgraph.root_discovery import (
    CompletionTelemetryRow,
    ConstructorFamilyCard,
    ObstructionCandidate,
    RootCandidate,
    RootDiscoveryScore,
    RootDiscoverySignals,
    attach_root_discovery_scores,
    build_constructor_family_cards,
    build_replay_queue,
    distill_obstruction_candidates,
    distill_root_candidates,
    score_root_candidate,
    score_root_candidates,
    summarize_root_discovery,
)
from mathgraph.persistent_filtration import (
    FiltrationEvidence,
    FiltrationSpec,
    PersistentFiltrationSummary,
    build_filtration_evidence,
    default_filtration_specs,
    summarize_persistence,
)
from mathgraph.root_shadow_collapse import (
    RootShadowCollapseResult,
    ShadowLink,
    choose_canonical_root,
    collapse_root_shadows,
    root_overlap_score,
)
from mathgraph.root_promotion import (
    RootPromotionPolicy,
    RootPromotionRecord,
    promote_roots,
    promotion_summary,
)
from mathgraph.root_compiler import (
    ConstructorPlan,
    choose_constructor_type,
    compile_constructor_plans,
)
from mathgraph.root_constructor_lab import (
    ConstructorFamilyResult,
    RootBasinPair,
    RootConstructorLabReport,
    RootHypothesis,
    RootValidationResult,
    default_root_hypotheses,
    detect_root_basin,
    run_root_constructor_lab,
    score_pair_for_root,
)
from mathgraph.continuation_traces import (
    ContinuationTrace,
    ContinuationTraceStore,
    make_trace_id,
)
from mathgraph.replay_engine import (
    ReplayReport,
    RouteReplaySignal,
    replay_continuation_traces,
)
from mathgraph.route_policy_v2 import (
    RoutePolicyV2Card,
    RoutePolicyV2Report,
    build_route_policy_v2_from_replay,
    build_route_policy_v2_from_trace_store,
    write_route_policy_v2,
)
from mathgraph.route_policy_scheduler_adapter import (
    RoutePriorityHint,
    match_priority_hint,
    route_policy_to_priority_hints,
)
from mathgraph.residual_atlas import (
    ResidualAtlasReport,
    ResidualCase,
    ResidualCluster,
    build_residual_atlas_from_rows,
    build_residual_atlas_from_traces,
    write_residual_atlas,
)
from mathgraph.frontier_v2 import (
    FrontierTaskV2,
    FrontierV2Report,
    build_frontier_v2_from_atlas,
    frontier_v2_to_task_queue_rows,
    write_frontier_v2,
)
from mathgraph.episode_runner_v2 import (
    EpisodeRunnerV2Config,
    EpisodeRunnerV2Report,
    EpisodeTaskResult,
    run_episode_v2,
)
from mathgraph.multi_episode_harness import (
    EpisodeSummaryRow,
    MultiEpisodeConfig,
    MultiEpisodeReport,
    run_multi_episode_harness,
)
from mathgraph.root_oracle import RootNodeOracle
from mathgraph.route_instructor import (
    RouteInstruction,
    build_all_route_instructions,
    build_route_instruction,
    route_instruction_report,
)
from mathgraph.route_learner import (
    RouteBasinKey,
    RouteLearner,
    RouteLearnerStats,
    RoutePolicyCard,
    RouteRecommendation,
    make_basin_key,
)
from mathgraph.task_planner import (
    CertificateTask,
    plan_certificate_task,
    plan_many_certificate_tasks,
)
from mathgraph.task_queue import (
    TaskQueueConfig,
    TaskQueueItem,
    TaskQueueResult,
    build_task_queue,
)
from mathgraph.task_runner import (
    TaskOutcome,
    TaskRunSummary,
    execute_certificate_task,
    execute_many_certificate_tasks,
    read_outcomes_json,
    read_outcomes_jsonl,
    residual_outcomes,
    summarize_task_outcomes,
    write_outcomes_json,
    write_outcomes_jsonl,
)
from mathgraph.terms import Term, parse_term
from mathgraph.trace import Trace
from mathgraph.trust import ProvenanceType, TrustLevel
from mathgraph.verify_api import MathGraphVerifier, VerifyConfig, VerifyRequest, VerifyResult

__all__ = [
    "AgentBiography",
    "AgentExperience",
    "AgentExperienceOutcome",
    "AgentProfile",
    "AgentStatus",
    "AlchemicalPhase",
    "AlchemicalStatus",
    "AlchemicalStep",
    "AlchemicalTrace",
    "Certificate",
    "CertificateAssimilationConfig",
    "CertificateAssimilationResult",
    "CertificateAssimilationSummary",
    "CertificateCorpus",
    "CertificateLawbook",
    "AcceptedLawbookStore",
    "LawbookAcceptanceBoundary",
    "LawbookEntry",
    "LawbookEntryKind",
    "LawbookEntryStatus",
    "LawbookReview",
    "LawbookReviewDecision",
    "LawbookStoreStatus",
    "KnownSkipDecision",
    "LawbookQuery",
    "LawbookQueryAnswer",
    "LawbookQueryKind",
    "LawbookQueryReport",
    "LawbookQueryReportStatus",
    "LawbookQueryStatus",
    "LawbookTrustLevel",
    "CertificateTask",
    "ConstructorPressure",
    "AssetDiscoveryConfig",
    "AssetDiscoveryResult",
    "AssetMaterializationConfig",
    "AssetMaterializationResult",
    "AssimilationLearningRecord",
    "ChewingSmokeConfig",
    "ChewingSmokeResult",
    "ChewingSmokeStageResult",
    "CompoundingDiagnostics",
    "CountermodelImportConfig",
    "CountermodelImportResult",
    "CountermodelImportRunResult",
    "DerivedCertificate",
    "DerivedCertificateGenerator",
    "DerivedCertificateStats",
    "DomainKernel",
    "Equation",
    "GeneralClaim",
    "EpisodeLearningConfig",
    "EpisodeLearningResult",
    "EpisodeRunnerV2Config",
    "EpisodeRunnerV2Report",
    "EpisodeTaskResult",
    "EpisodeSummaryRow",
    "FiniteCountermodelConfig",
    "FiniteCountermodelResult",
    "FiniteCountermodelRunResult",
    "FlywheelConfig",
    "FlywheelResult",
    "FlywheelStageResult",
    "FrontierBuilderConfig",
    "FrontierBuilderResult",
    "FrontierCandidate",
    "FrontierTaskV2",
    "FrontierV2Report",
    "HTiltLiteScore",
    "HTiltScheduler",
    "HTiltSchedulerStats",
    "HTiltScoreBreakdown",
    "HostVerifier",
    "ImportedTheoryObject",
    "ImportedTheoryRelation",
    "Kernel",
    "KernelOracle",
    "KnownPairFilter",
    "JsonlLedger",
    "LawbookStore",
    "LawbookStoreStats",
    "MathGraphVerifier",
    "OracleAnswer",
    "ObstructionNode",
    "OutcomeDatasetBuilder",
    "OutcomeDatasetStats",
    "PairAdvice",
    "PairOutcome",
    "ProvenanceType",
    "ProjectionCandidate",
    "ProjectionResult",
    "ProjectionRuleKind",
    "ProjectionStatus",
    "ProjectionTrace",
    "ReasonNode",
    "RefutationCertificate",
    "RoadmapAlignmentFinding",
    "RoadmapAlignmentReport",
    "RouteBasinKey",
    "RouteLearner",
    "RouteLearnerStats",
    "RouteYieldStats",
    "ConstructorYieldStats",
    "ResidualBasinStats",
    "RootAlias",
    "RootCertificateCoverage",
    "TaskOutcome",
    "TaskQueueConfig",
    "TaskQueueItem",
    "TaskQueueResult",
    "TaskRunSummary",
    "canonical_json",
    "RouteInstruction",
    "RootNode",
    "RootNodeOracle",
    "CompletionTelemetryRow",
    "ConstructorPlan",
    "ConstructorFamilyCard",
    "ConstructorFamilyResult",
    "ConstructorAttempt",
    "ContinuationTrace",
    "ContinuationTraceStore",
    "FiltrationEvidence",
    "FiltrationSpec",
    "ObstructionCandidate",
    "PersistentFiltrationSummary",
    "ReplayReport",
    "ResidualAtlasReport",
    "ResidualCase",
    "ResidualCluster",
    "RouteReplaySignal",
    "RoutePolicyV2Card",
    "RoutePolicyV2Report",
    "RoutePriorityHint",
    "RootBasinPair",
    "RootCandidate",
    "RootAwareConstructorPlan",
    "RootConstructorLabReport",
    "RootConstructorKind",
    "RootConstructorStatus",
    "RootConstructorTrace",
    "RootDiscoveryScore",
    "RootDiscoverySignals",
    "RootHypothesis",
    "RootPromotionPolicy",
    "RootPromotionRecord",
    "RootShadowCollapseResult",
    "RootValidationResult",
    "ShadowLink",
    "attach_root_discovery_scores",
    "build_filtration_evidence",
    "build_constructor_family_cards",
    "build_replay_queue",
    "build_frontier_v2_from_atlas",
    "build_route_policy_v2_from_replay",
    "build_route_policy_v2_from_trace_store",
    "build_residual_atlas_from_rows",
    "build_residual_atlas_from_traces",
    "choose_canonical_root",
    "choose_constructor_type",
    "choose_episode_routes",
    "collapse_root_shadows",
    "compile_constructor_plans",
    "compile_root_constructor_plans",
    "combine_episode_alchemical_trace",
    "default_filtration_specs",
    "default_root_hypotheses",
    "detect_root_basin",
    "distill_obstruction_candidates",
    "distill_root_candidates",
    "promote_roots",
    "promotion_summary",
    "root_overlap_score",
    "run_root_constructor_lab",
    "make_alchemical_trace_id",
    "make_trace_id",
    "match_priority_hint",
    "replay_continuation_traces",
    "route_policy_to_priority_hints",
    "score_root_candidate",
    "score_root_candidates",
    "score_pair_for_root",
    "score_route_htilt_lite",
    "summarize_persistence",
    "summarize_root_discovery",
    "write_route_policy_v2",
    "write_residual_atlas",
    "frontier_v2_to_task_queue_rows",
    "write_frontier_v2",
    "RootObstructionLink",
    "RootReasonLink",
    "RootSignal",
    "RoutePolicyCard",
    "RouteRecommendation",
    "ScheduledTask",
    "SchedulerInputPair",
    "SemanticEmbedding",
    "SemanticEmbeddingKind",
    "build_all_route_instructions",
    "build_route_instruction",
    "build_candidate_frontier",
    "build_task_queue",
    "check_roadmap_alignment",
    "advisory_similarity_projection",
    "advise_many",
    "advise_pair",
    "content_id",
    "consolidate_root_nodes",
    "discover_mathgraph_assets",
    "extract_pair_features",
    "extract_outcome_pair_features",
    "execute_certificate_task",
    "execute_many_certificate_tasks",
    "exact_known_projection",
    "hash_certificate",
    "hash_file",
    "hash_trace",
    "import_finite_countermodel_results",
    "import_closure_oracle_csv",
    "import_table_registry_csv",
    "import_v16_6_2_elevated_false_dir",
    "import_v16_7_root_atlas_dir",
    "learn_from_assimilation_episodes",
    "load_v1662_elevated_false_certificates",
    "load_v167_obstructions",
    "load_v167_reason_nodes",
    "load_v167_root_nodes",
    "load_constructor_plans_jsonl",
    "load_root_signals_json",
    "load_root_signals_jsonl",
    "make_basin_key",
    "make_external_theory_domain_kernel",
    "make_constructor_attempt_id",
    "make_constructor_plan_id",
    "make_projection_candidate_id",
    "make_projection_result_id",
    "make_projection_trace_id",
    "make_root_constructor_trace_id",
    "make_root_signal_id",
    "materialize_mathgraph_assets",
    "sha256_hex",
    "sha256_json",
    "sha256_text",
    "Term",
    "TerminalForm",
    "parse_equation",
    "parse_term",
    "plan_certificate_task",
    "plan_many_certificate_tasks",
    "read_outcomes_json",
    "read_outcomes_jsonl",
    "residual_outcomes",
    "register_external_theory_kernel",
    "register_domain_kernel_in_store",
    "register_etp_kernel",
    "projection_trace_to_agent_experiences",
    "projection_trace_to_alchemical_trace",
    "root_constructor_trace_to_agent_experiences",
    "root_constructor_trace_to_alchemical_trace",
    "root_constructor_trace_to_projection_candidates",
    "route_instruction_report",
    "run_mathgraph_flywheel",
    "run_chewing_smoke",
    "run_certificate_assimilation",
    "run_finite_countermodel_tasks",
    "run_projection_engine",
    "run_constructor_attempts",
    "run_root_aware_constructors",
    "summarize_task_outcomes",
    "source_weakening_false_projection",
    "target_strengthening_false_projection",
    "transitivity_projection",
    "Trace",
    "TrustLevel",
    "TheoryObjectKind",
    "TheoryRelationKind",
    "VerificationStatus",
    "VerifyConfig",
    "VerifyRequest",
    "VerifyResult",
    "write_outcomes_json",
    "write_outcomes_jsonl",
    "ArtifactRisk",
    "AnalyticTruth",
    "ContainmentMode",
    "DenotationRecord",
    "DenotationStatus",
    "DomainKernelSemanticEmbedding",
    "EmbeddingKind",
    "ExtensionalCollapsePolicy",
    "FormalWorld",
    "FormalWorldKind",
    "GuardSeverity",
    "HyperintensionalIdentityMode",
    "ImportedTheoryObjectKind",
    "LanguageFragment",
    "MathGraphType",
    "ObjectIdentityMode",
    "ParadoxGuard",
    "ParadoxGuardKind",
    "ParadoxGuardResult",
    "PredicateKind",
    "PredicationFact",
    "PredicationMode",
    "ProofTransportStatus",
    "ReasonContainmentRecord",
    "TheoryDenotation",
    "TheoryObjectificationMap",
    "TheoryReading",
    "TypeParseError",
    "TypedObject",
    "UniquenessStatus",
    "external_theory_formal_world_precedent",
    "external_theory_precedent_fragment",
    "canonical_encoded_object_id",
    "can_promote_denotation",
    "encodes",
    "etp_magma_equations_fragment",
    "etp_magma_formal_world",
    "exemplifies",
    "make_etp_domain_kernel",
    "normalize_type_expr",
    "parse_type_expr",
    "require_denotes",
    "semantic_embedding_artifact_guard",
    "set_collapse_guard",
    "should_merge_objects",
    "FormulaRole",
    "HostObjectTheoremLink",
    "InferenceRule",
    "IsabelleExportRecord",
    "IsabelleExportStatus",
    "ObjectLanguageFormula",
    "ObjectLanguageKind",
    "ObjectLanguageTerm",
    "ProofMethod",
    "ProofMethodKind",
    "ProofArtifact",
    "ProofArtifactKind",
    "ProofVerificationResult",
    "ProofVerificationStatus",
    "ProofVerificationTrace",
    "ProofVerifierKind",
    "DigestionArtifactKind",
    "DigestionStatus",
    "ExpositionNote",
    "KeyIdeaCandidate",
    "LawbookAssimilationCandidate",
    "ProofDependencyMap",
    "ProofDigestionTrace",
    "ProofStepDigest",
    "ReusableSchemaCandidate",
    "TheoryDeclaration",
    "TheoryDeclarationKind",
    "normalize_object_language_text",
    "AutomationBias",
    "BackendRole",
    "BenchmarkCase",
    "BenchmarkExpectedStatus",
    "BenchmarkObservedStatus",
    "BenchmarkResult",
    "BenchmarkRun",
    "BenchmarkSuite",
    "ChoicePointStatus",
    "CombinationMethod",
    "CompletenessStatus",
    "ConflictPolicy",
    "CorrespondenceClaim",
    "CorrespondenceDirection",
    "CorrespondenceStatus",
    "EmbeddingStrategy",
    "EmbeddingStrategyProfile",
    "FaithfulnessAssessment",
    "FaithfulnessStatus",
    "InterpretationChoicePoint",
    "LogicCombination",
    "LogicWorkbench",
    "ModelFinderResult",
    "ModelFinderStatus",
    "ProofFinderResult",
    "ProofFinderStatus",
    "SemanticsRepresentation",
    "SoundnessStatus",
    "SyntaxRepresentation",
    "VerifierBackendKind",
    "VerifierBackendProfile",
    "VerificationEpisodeInput",
    "VerificationEpisodeRouteDecision",
    "VerificationEpisodeStatus",
    "VerificationEpisodeTrace",
    "VerificationRouteKind",
    "HTiltTelemetrySummary",
    "RouteTelemetryEvent",
    "RouteTelemetryKind",
    "RouteTelemetryLedger",
    "RouteTelemetryOutcome",
    "SpectralHTiltConfig",
    "SpectralHTiltEstimate",
    "SpectralStateEstimate",
    "AdvisoryOnlyAdapter",
    "ClaimIRStatus",
    "ClaimKind",
    "ClaimParseResult",
    "DomainAdapter",
    "DomainClaim",
    "DomainFormalWorld",
    "DomainFormalWorldKind",
    "FormalWorldRegistry",
    "LeanSkeletonAdapter",
    "MagmaEquationalAdapter",
    "LeanAdapterTrace",
    "LeanArtifactStatus",
    "LeanCheckResult",
    "LeanEnvironment",
    "LeanFileArtifact",
    "ContinuationAction",
    "ContinuationActionInput",
    "ContinuationActionKind",
    "ContinuationActionOutput",
    "ContinuationActionRegistry",
    "ContinuationActionStatus",
    "ContinuationActionTrace",
    "ContinuationOutputKind",
    "FlawSeverity",
    "RepairActionKind",
    "RepairLoopStatus",
    "RepairLoopTrace",
    "RepairPlan",
    "VerifierFeedback",
    "VerifierFeedbackStatus",
    "WorkbenchLayer",
    "WorkbenchLifecycleStatus",
    "build_reference_logic_workbench_bundle",
    "build_mathgraph_etp_workbench_bundle",
    "etp_matrix_benchmark_suite_metadata",
    "isabelle_nitpick_backend_placeholder",
    "isabelle_nunchaku_backend_placeholder",
    "isabelle_sledgehammer_backend_placeholder",
    "lean_backend_placeholder",
    "reference_methodology_benchmark_suite_metadata",
    "reference_logic_workbench",
    "mathgraph_default_workbench",
    "python_finite_table_checker_backend",
    "ProofMotif",
    "ProofMotifKind",
    "ProofRouteStatus",
    "make_proof_motif_id",
    "infer_proof_motif_kind",
    "LemmaCandidate",
    "LemmaCandidateStatus",
    "CutIntroductionKind",
    "chain_audit_proof",
    "import_verified_proof",
    "make_cut_candidate",
    "make_lean_skeleton",
    "make_lemma_candidate",
    "make_lemma_candidate_id",
    "make_proof_artifact_id",
    "make_proof_result_id",
    "make_proof_trace_id",
    "make_theorem_schema",
    "make_route_telemetry_event_id",
    "make_route_telemetry_ledger_id",
    "make_domain_claim_id",
    "make_verification_episode_id",
    "canonical_lemma_name",
    "LeanArtifact",
    "LeanArtifactKind",
    "LeanVerificationStatus",
    "render_lean_skeleton",
    "ProofAtlas",
    "build_proof_atlas_from_true_rows",
    "discover_true_proof_artifacts",
    "load_true_proof_rows",
    "normalize_true_proof_row",
    "import_true_proof_artifacts_to_store",
    "MetabolicCycleConfig",
    "MetabolicCycleResult",
    "MetabolicCycleStageResult",
    "MetabolicDiagnostics",
    "M0EpisodeConfig",
    "M0EpisodeMetrics",
    "M0EpisodeResult",
    "M0PairResult",
    "MultiEpisodeConfig",
    "MultiEpisodeReport",
    "MathGraphAnswer",
    "MathGraphAuditError",
    "MathGraphClient",
    "MathGraphClientConfig",
    "MathGraphHTTPServer",
    "MathGraphRequestHandler",
    "AuditFinding",
    "AuditReport",
    "TerminalContractResult",
    "VerifierBoundary",
    "build_synthetic_metabolic_frontier",
    "compute_derived_amplification_factor",
    "compute_residual_compression_gain",
    "evaluate_better_shaped_unknown",
    "run_m0_episode",
    "run_episode_v2",
    "run_multi_episode_harness",
    "proof_verification_trace_to_agent_experiences",
    "proof_verification_trace_to_alchemical_trace",
    "proof_verification_trace_to_projection_candidates",
    "run_proof_verification_pipeline",
    "run_proof_verifier",
    "classify_proof_steps",
    "digest_lean_adapter_trace",
    "digest_proof_artifact",
    "digest_proof_verification_trace",
    "digest_verification_episode_trace",
    "extract_dependencies_from_proof_artifact",
    "extract_key_ideas",
    "extract_reusable_schemas",
    "make_assimilation_candidate_id",
    "make_dependency_map_id",
    "make_exposition_note",
    "make_exposition_note_id",
    "make_key_idea_id",
    "make_lawbook_assimilation_candidate",
    "make_proof_digestion_trace_id",
    "make_schema_id",
    "make_step_digest_id",
    "proof_artifact_from_content",
    "proof_digestion_trace_to_agent_experiences",
    "proof_digestion_trace_to_alchemical_trace",
    "proof_digestion_trace_to_continuation_outputs",
    "proof_digestion_trace_to_projection_candidates",
    "build_route_telemetry_ledger",
    "build_generator_K",
    "build_killing_pressure_from_ledger",
    "build_transition_matrix_from_ledger",
    "compute_multiplicative_bridge",
    "compute_survivor_distribution",
    "estimate_left_support_q",
    "estimate_right_survival_h",
    "estimate_spectral_htilt",
    "killing_table",
    "l1_error",
    "multiply_matrix_vector",
    "multiply_transpose_matrix_vector",
    "normalize_vector",
    "route_outcome_table",
    "route_priorities_from_estimate",
    "default_formal_world_registry",
    "domain_claim_to_verification_episode_input",
    "check_lean_file",
    "detect_lean_environment",
    "extract_lean_imports",
    "extract_lean_theorem_names",
    "get_default_domain_adapters",
    "import_checked_lean_artifact",
    "lean_adapter_trace_to_agent_experiences",
    "lean_adapter_trace_to_alchemical_trace",
    "lean_adapter_trace_to_proof_verification_trace",
    "lean_file_from_proof_artifact",
    "make_continuation_action_id",
    "make_continuation_input_id",
    "make_continuation_output_id",
    "make_continuation_registry_id",
    "make_continuation_trace_id",
    "make_lean_adapter_trace_id",
    "make_lean_check_result_id",
    "make_lean_file_id",
    "normalize_domain_claim",
    "parse_domain_claim",
    "proof_artifact_from_lean_file",
    "route_domain_claim_to_existing_inputs",
    "run_lean_adapter_pipeline",
    "run_domain_claim_pipeline",
    "apply_continuation_action",
    "continuation_outputs_to_episode_inputs",
    "continuation_outputs_to_projection_candidates",
    "continuation_outputs_to_proof_artifacts",
    "continuation_trace_to_agent_experiences",
    "continuation_trace_to_alchemical_trace",
    "default_continuation_action_registry",
    "drop_variable_from_expr",
    "dualize_magma_expression",
    "form_equivalence_claim",
    "form_implication_claim",
    "identify_variables_in_expr",
    "negate_target_task",
    "run_continuation_actions",
    "ContinuationCurriculum",
    "CurriculumBuildStrategy",
    "CurriculumStage",
    "CurriculumStageKind",
    "CurriculumStageStatus",
    "CurriculumTraceStatus",
    "build_continuation_curriculum",
    "build_curriculum_from_actions",
    "build_curriculum_from_proof_digestion",
    "build_curriculum_from_projection_candidates",
    "build_curriculum_from_repair_loop",
    "build_curriculum_from_verifier_feedback",
    "build_empty_curriculum",
    "build_magma_equational_curriculum",
    "curriculum_to_agent_experiences",
    "curriculum_to_alchemical_trace",
    "curriculum_to_continuation_outputs",
    "curriculum_to_episode_inputs",
    "curriculum_to_projection_candidates",
    "curriculum_to_route_telemetry_events",
    "make_curriculum_id",
    "make_curriculum_stage_id",
    "normalize_curriculum_target",
    "DiscoveryValueDecision",
    "DiscoveryValueObjectKind",
    "DiscoveryValueReport",
    "DiscoveryValueScore",
    "DiscoveryValueSignal",
    "DiscoveryValueSignalKind",
    "DiscoveryValueStatus",
    "build_discovery_value_report",
    "discovery_value_report_to_agent_experiences",
    "discovery_value_report_to_alchemical_trace",
    "discovery_value_report_to_continuation_outputs",
    "discovery_value_report_to_curriculum",
    "discovery_value_report_to_route_telemetry_events",
    "make_discovery_value_report_id",
    "make_discovery_value_score_id",
    "make_discovery_value_signal_id",
    "accept_lawbook_entry",
    "audit_lawbook_entry",
    "audit_lawbook_store",
    "build_lawbook_store",
    "lawbook_entry_from_assimilation_candidate",
    "lawbook_entry_from_certificate_like",
    "lawbook_entry_from_discovery_value_score",
    "lawbook_entry_from_projection_candidate",
    "lawbook_entry_from_proof_digestion",
    "lawbook_store_to_agent_experiences",
    "lawbook_store_to_alchemical_trace",
    "lawbook_store_to_continuation_outputs",
    "lawbook_store_to_projection_candidates",
    "lawbook_store_to_route_telemetry_events",
    "make_lawbook_entry_id",
    "make_lawbook_review_id",
    "make_lawbook_store_id",
    "review_lawbook_candidate",
    "build_lawbook_trust_summary",
    "explain_lawbook_answer",
    "known_skip_for_claim",
    "lawbook_query_answer_to_continuation_outputs",
    "lawbook_query_answer_to_projection_candidates",
    "lawbook_query_report_to_agent_experiences",
    "lawbook_query_report_to_alchemical_trace",
    "lawbook_query_report_to_route_telemetry_events",
    "make_certificate_query",
    "make_claim_query",
    "make_entry_query",
    "make_known_skip_query",
    "make_lawbook_query_answer_id",
    "make_lawbook_query_id",
    "make_lawbook_query_report_id",
    "make_trust_summary_query",
    "query_lawbook_store",
    "query_lawbook_store_by_certificate",
    "query_lawbook_store_by_claim",
    "query_lawbook_store_by_entry",
    "query_lawbook_store_many",
    "StructuralEdge",
    "StructuralEdgeKind",
    "StructuralGraph",
    "StructuralIdentityReport",
    "StructuralIdentityReportStatus",
    "StructuralMatchKind",
    "StructuralMergeCandidate",
    "StructuralMergeDecision",
    "StructuralNode",
    "StructuralNodeKind",
    "StructuralObjectKind",
    "StructuralSignature",
    "audit_structural_identity_report",
    "audit_structural_merge_candidate",
    "build_structural_identity_report",
    "compare_structural_signatures",
    "compute_structural_signature",
    "find_structural_merge_candidates",
    "make_structural_edge_id",
    "make_structural_graph_id",
    "make_structural_identity_report_id",
    "make_structural_merge_candidate_id",
    "make_structural_node_id",
    "make_structural_signature_id",
    "structural_graph_from_agent_experience",
    "structural_graph_from_alchemical_trace",
    "structural_graph_from_curriculum",
    "structural_graph_from_curriculum_stage",
    "structural_graph_from_discovery_value_score",
    "structural_graph_from_lawbook_entry",
    "structural_graph_from_lawbook_query_answer",
    "structural_graph_from_lawbook_store",
    "structural_graph_from_mapping",
    "structural_graph_from_object",
    "structural_graph_from_projection_candidate",
    "structural_graph_from_proof_digestion_trace",
    "structural_graph_from_repair_loop",
    "structural_graph_from_verifier_feedback",
    "structural_identity_report_to_agent_experiences",
    "structural_identity_report_to_alchemical_trace",
    "structural_identity_report_to_continuation_outputs",
    "structural_identity_report_to_curriculum",
    "structural_identity_report_to_lawbook_candidates",
    "structural_identity_report_to_route_telemetry_events",
    "HabitCandidate","HabitFormationReport","HabitFormationReportStatus","HabitObservation",
    "HabitObservationKind","HabitOutcome","HabitReview","HabitReviewDecision","HabitRule",
    "HabitRuleKind","HabitStatus","HabitStore","apply_habit_rules","audit_habit_candidate",
    "audit_habit_report","audit_habit_rule","build_habit_candidates","build_habit_formation_report",
    "build_habit_store","habit_observations_from_object","habit_report_to_agent_experiences",
    "habit_report_to_alchemical_trace","habit_report_to_continuation_outputs","habit_report_to_curriculum",
    "habit_report_to_discovery_value_scores","habit_report_to_lawbook_candidates","habit_report_to_route_telemetry_events",
    "infer_condition_key","infer_rule_kind","make_habit_candidate_id","make_habit_formation_report_id",
    "make_habit_observation_id","make_habit_review_id","make_habit_rule_id","make_habit_store_id",
    "promote_habit_candidate","rank_routes_with_habits","review_habit_candidate",
    "ReasonAtomKind","ReasonCandidate","ReasonCandidateKind","ReasonCompressionReport",
    "ReasonCompressionReportStatus","ReasonNode","ReasonObservation","ReasonObservationKind",
    "ReasonReview","ReasonReviewDecision","ReasonStatus","apply_reason_nodes","audit_reason_candidate",
    "audit_reason_node","audit_reason_report","build_reason_candidates","build_reason_compression_report",
    "check_reason_minimality","classify_atom_kind","extract_atoms_from_mapping","make_reason_candidate_id",
    "make_reason_compression_report_id","make_reason_node_id","make_reason_observation_id","make_reason_review_id",
    "normalize_reason_atom","promote_reason_candidate","rank_routes_with_reasons","reason_observations_from_object",
    "reason_report_to_agent_experiences","reason_report_to_alchemical_trace","reason_report_to_continuation_outputs",
    "reason_report_to_curriculum","reason_report_to_discovery_value_scores","reason_report_to_lawbook_candidates",
    "reason_report_to_route_telemetry_events","reason_report_to_structural_identity_objects","review_reason_candidate",
    "ProcessContextItem","ProcessContextKind","ProcessContextRole","ProcessElimination",
    "ProcessEliminationKind","ProcessEpisodeRecord","ProcessEpisodeStatus","ProcessMemoryAnswer",
    "ProcessMemoryAnswerStatus","ProcessMemoryQuery","ProcessMemoryQueryKind","ProcessMemoryReport",
    "ProcessMemoryReportStatus","ProcessMemoryStore","ProcessTransition","ProcessTransitionKind",
    "audit_process_context_item","audit_process_episode_record","audit_process_memory_answer",
    "audit_process_memory_report","build_process_memory_store","explain_process_memory_answer",
    "make_process_context_id","make_process_elimination_id","make_process_episode_id",
    "make_process_memory_answer_id","make_process_memory_query_id","make_process_memory_report_id",
    "make_process_memory_store_id","make_process_query_by_agent","make_process_query_by_certificate",
    "make_process_query_by_claim","make_process_query_by_episode","make_process_query_by_habit_rule",
    "make_process_query_by_lawbook_entry","make_process_query_by_reason_node","make_process_query_by_route",
    "make_process_text_query","make_process_transition_id","make_process_trust_summary_query",
    "process_episode_from_object","process_report_to_agent_experiences","process_report_to_alchemical_trace",
    "process_report_to_continuation_outputs","process_report_to_curriculum",
    "process_report_to_discovery_value_scores","process_report_to_habit_observations",
    "process_report_to_lawbook_candidates","process_report_to_reason_observations",
    "process_report_to_route_telemetry_events","process_report_to_structural_identity_objects",
    "query_process_memory_store","query_process_memory_store_many","summarize_eliminations",
    "summarize_route_processes","trace_episode_lineage",
    "ProjectionCompatibility","StructureDescriptor","StructureFamily","StructureFeatureKind",
    "StructureMapping","StructureObjectKind","StructureRegistryEntry","StructureRegistryReport",
    "StructureRegistryReportStatus","StructureRegistryStore","StructureType","TypedProjectionCandidate",
    "TypedProjectionStatus","audit_structure_descriptor","audit_structure_mapping",
    "audit_structure_registry_report","audit_typed_projection_candidate","build_structure_mappings",
    "build_structure_registry_report","build_structure_registry_store","build_typed_projection_candidates",
    "classify_structure_feature","compute_structure_mapping","default_structure_types",
    "extract_structure_features_from_mapping","infer_structure_families","make_structure_descriptor_id",
    "make_structure_mapping_id","make_structure_registry_entry_id","make_structure_registry_report_id",
    "make_structure_registry_store_id","make_structure_type_id","make_typed_projection_candidate_id",
    "normalize_structure_atom","structure_descriptors_from_object","structure_report_to_agent_experiences",
    "structure_report_to_alchemical_trace","structure_report_to_continuation_outputs",
    "structure_report_to_curriculum","structure_report_to_discovery_value_scores",
    "structure_report_to_habit_observations","structure_report_to_lawbook_candidates",
    "structure_report_to_process_episodes","structure_report_to_projection_candidates",
    "structure_report_to_reason_observations","structure_report_to_route_telemetry_events",
    "structure_report_to_structural_identity_objects","typed_projection_candidate_from_mapping",
    "RoleCandidateStatus","RoleConditionKind","RoleConjectureCandidate","RoleConjectureKind",
    "RoleDefinitionCandidate","RoleObject","RoleObjectKind","RoleObjectReport","RoleObjectReportStatus",
    "RoleReview","RoleReviewDecision","RoleSignature","RoleSourceKind","RoleWitnessCandidate",
    "RoleWitnessStatus","apply_role_objects_to_routes","audit_role_conjecture_candidate",
    "audit_role_definition_candidate","audit_role_object","audit_role_object_report",
    "audit_role_signature","audit_role_witness_candidate","build_role_conjecture_candidates",
    "build_role_definition_candidates","build_role_object_report","build_role_witness_candidates",
    "classify_role_condition","extract_role_conditions_from_mapping","infer_role_kind",
    "make_role_conjecture_candidate_id","make_role_definition_candidate_id","make_role_object_id",
    "make_role_object_report_id","make_role_review_id","make_role_signature_id",
    "make_role_witness_candidate_id","normalize_role_atom","promote_role_definition_candidate",
    "propose_role_name","rank_routes_with_role_objects","review_role_definition_candidate",
    "role_report_to_agent_experiences","role_report_to_alchemical_trace",
    "role_report_to_continuation_outputs","role_report_to_curriculum",
    "role_report_to_discovery_value_scores","role_report_to_habit_observations",
    "role_report_to_lawbook_candidates","role_report_to_process_episodes",
    "role_report_to_reason_observations","role_report_to_route_telemetry_events",
    "role_report_to_structure_descriptors","role_report_to_structural_identity_objects",
    "role_report_to_typed_projection_candidates","role_signatures_from_object",
    "AnalogyBreak","AnalogyBreakKind","AnalogyCandidateStatus","AnalogyExpositionNote",
    "AnalogyFeatureKind","AnalogyFeatureMap","AnalogyRelationKind","AnalogyReview",
    "AnalogyReviewDecision","AnalogySource","AnalogySourceKind","ExpositionNoteKind",
    "StructuralAnalogyCandidate","StructuralAnalogyReport","StructuralAnalogyReportStatus",
    "analogy_report_to_agent_experiences","analogy_report_to_alchemical_trace",
    "analogy_report_to_continuation_outputs","analogy_report_to_curriculum",
    "analogy_report_to_discovery_value_scores","analogy_report_to_habit_observations",
    "analogy_report_to_lawbook_candidates","analogy_report_to_process_episodes",
    "analogy_report_to_reason_observations","analogy_report_to_role_signatures",
    "analogy_report_to_route_telemetry_events","analogy_report_to_structural_identity_objects",
    "analogy_report_to_structure_descriptors","analogy_report_to_typed_projection_candidates",
    "analogy_sources_from_object","apply_analogy_candidates_to_routes","audit_analogy_break",
    "audit_analogy_feature_map","audit_analogy_source","audit_exposition_note",
    "audit_structural_analogy_candidate","audit_structural_analogy_report",
    "build_analogy_feature_maps","build_structural_analogy_candidates",
    "build_structural_analogy_report","classify_analogy_feature","compute_analogy_feature_map",
    "exposition_notes_from_candidate","extract_analogy_features_from_mapping",
    "identify_analogy_breaks","infer_analogy_relation_kind","make_analogy_break_id",
    "make_analogy_exposition_note_id","make_analogy_feature_map_id","make_analogy_review_id",
    "make_analogy_source_id","make_structural_analogy_candidate_id",
    "make_structural_analogy_report_id","normalize_analogy_atom",
    "rank_routes_with_analogies","review_structural_analogy_candidate",
    "structural_analogy_candidate_from_map",
    "AdapterFormalWorldKind","AdapterOperation","AdapterSupportLevel",
    "FormalWorldAdapterCapability","FormalWorldAdapterReport","FormalWorldAdapterReportStatus",
    "FormalWorldAdapterSpec","FormalWorldHandoff","FormalWorldNormalizeResult",
    "FormalWorldParseResult","FormalWorldTask","FormalWorldTaskKind","FormalWorldValidationResult",
    "HandoffKind","HandoffStatus","NormalizeStatus","ParseStatus","ValidationStatus",
    "adapter_report_to_agent_experiences","adapter_report_to_alchemical_trace",
    "adapter_report_to_analogy_sources","adapter_report_to_continuation_outputs",
    "adapter_report_to_curriculum","adapter_report_to_discovery_value_scores",
    "adapter_report_to_habit_observations","adapter_report_to_lawbook_candidates",
    "adapter_report_to_process_episodes","adapter_report_to_reason_observations",
    "adapter_report_to_role_signatures","adapter_report_to_route_telemetry_events",
    "adapter_report_to_structural_identity_objects","adapter_report_to_structure_descriptors",
    "adapter_report_to_typed_projection_candidates","adapter_spec_for_world",
    "audit_adapter_capability","audit_adapter_spec","audit_formal_world_adapter_report",
    "audit_formal_world_handoff","audit_formal_world_task","audit_normalize_result",
    "audit_parse_result","audit_validation_result","build_formal_world_adapter_report",
    "default_formal_world_adapter_capabilities","default_formal_world_adapter_specs",
    "detect_formal_world_kind","formal_world_inputs_from_object","handoffs_from_tasks",
    "make_adapter_capability_id","make_adapter_spec_id","make_formal_world_adapter_report_id",
    "make_formal_world_handoff_id","make_formal_world_normalize_id","make_formal_world_parse_id",
    "make_formal_world_task_id","make_formal_world_validation_id","normalize_finite_structure_parse",
    "normalize_formal_world_parse","normalize_generic_formal_parse","normalize_lean_like_parse",
    "normalize_magma_equational_parse","normalize_proof_text_parse","parse_finite_structure",
    "parse_formal_world_input","parse_generic_formal","parse_lean_like",
    "parse_magma_equational","parse_proof_text","tasks_from_validation",
    "validate_formal_world_normalization",
    "CheckCommandKind","CheckRequestStatus","CheckResultStatus","ImportEdgeKind",
    "ProofSystemArtifactKind","ProofArtifactManifest","ProofSystemArtifactStatus",
    "ProofBoundaryEvidence","ProofBoundaryKind","ProofCheckCommandContract",
    "ProofCheckRequest","ProofCheckResult","ProofImportGraph","ProofProjectManifest",
    "ProofSystemIntegrationReport","ProofSystemIntegrationReportStatus","ProofSystemKind",
    "ProofSystemSpec","ProofSystemTask","ProofSystemTaskKind","TrustedImportStatus",
    "TrustedProofImportRecord","audit_proof_artifact_manifest",
    "audit_proof_boundary_evidence","audit_proof_check_command_contract",
    "audit_proof_check_request","audit_proof_check_result","audit_proof_import_graph",
    "audit_proof_project_manifest","audit_proof_system_integration_report",
    "audit_proof_system_spec","audit_proof_system_task","audit_trusted_proof_import_record",
    "build_proof_import_graph","build_proof_project_manifest",
    "build_proof_system_integration_report","create_check_request",
    "default_check_command_contract_for_artifact","default_proof_system_specs",
    "detect_proof_system_kind","extract_coq_imports","extract_coq_theorem_names",
    "extract_generic_proof_markers","extract_isabelle_imports","extract_isabelle_theorem_names",
    "proof_artifact_manifest_from_path","proof_artifact_manifest_from_text",
    "proof_boundary_evidence_from_check_result","proof_boundary_evidence_from_trusted_import",
    "proof_system_inputs_from_object","proof_system_report_to_agent_experiences",
    "proof_system_report_to_alchemical_trace","proof_system_report_to_analogy_sources",
    "proof_system_report_to_continuation_outputs","proof_system_report_to_curriculum",
    "proof_system_report_to_discovery_value_scores","proof_system_report_to_habit_observations",
    "proof_system_report_to_lawbook_candidates","proof_system_report_to_process_episodes",
    "proof_system_report_to_proof_digestion_inputs","proof_system_report_to_reason_observations",
    "proof_system_report_to_repair_traces","proof_system_report_to_role_signatures",
    "proof_system_report_to_route_telemetry_events","proof_system_report_to_structural_identity_objects",
    "proof_system_report_to_structure_descriptors","proof_system_report_to_typed_projection_candidates",
    "proof_system_report_to_verifier_feedback","proof_system_spec_for_kind",
    "proof_system_tasks_from_artifacts","proof_system_tasks_from_check_results",
    "proof_system_tasks_from_trusted_imports","trusted_import_record_from_mapping",
    "SemanticSourceKind","SemanticClaimKind","SemanticDomainKind","SemanticRiskLevel",
    "SemanticAmbiguityKind","SemanticExtractionKind","FormalizationRequestKind",
    "SemanticRouteTarget","SemanticIntakeTaskKind","SemanticIntakeReportStatus",
    "SemanticSource","SemanticClaimSegment","SemanticClaimClassification",
    "SemanticAmbiguity","SemanticExtraction","FormalizationRequest",
    "SemanticRoutingHint","SemanticIntakeTask","SemanticIntakeReport",
    "semantic_sources_from_object","segment_semantic_source","segment_semantic_sources",
    "classify_semantic_segment","detect_semantic_ambiguities","extract_semantic_items",
    "formalization_requests_from_semantic","semantic_routing_hints_from_semantic",
    "semantic_tasks_from_semantic","build_semantic_intake_report",
    "ApiRoute","ApiRequestKind","ApiResponseStatus","ApiTruthStatus",
    "ApiSafetyLevel","ApiArtifactKind","ApiRequest","ApiHealth",
    "ApiAuditResult","ApiRouteResult","ApiResponse","ApiServiceState",
    "MathGraphLocalClient",
    "ExistentialAgentStatus","AgentMortalityMode","PrivateStatePolicy",
    "AgentResourceKind","AgentWoundType","AgentWoundSeverity",
    "AgentValueDimension","HeldInChoraReason","AgentInheritanceMode",
    "AgentDaemonKind","AgentEcologyEventKind","AgentEcologyReportStatus",
    "AgentMortalityPolicy","AgentResourceAccount","AgentWound",
    "AgentValueProfile","AgentNarrative","HeldInChoraRecord",
    "AgentLineageRecord","AgentDaemon","ExistentialAgent",
    "AgentEcologyEvent","AgentEcologyReport","create_existential_agent",
    "build_agent_ecology_report",
    "HardeningCheckKind","HardeningCheckStatus","HardeningSeverity",
    "HardeningScenarioKind","HardeningArtifactKind","HardeningFinding",
    "HardeningScenario","HardeningCliResult","HardeningReplayManifest",
    "HardeningReport","build_hardening_report",
    "VerifierSystemKind","VerifierExecutableStatus","VerifierExecutionMode",
    "VerifierExecutionStatus","VerifierBoundaryStatus","VerifierSafetyFindingKind",
    "VerifierEvidenceKind","VerifierExecutable","VerifierCommandContract",
    "VerifierSafetyFinding","VerifierExecutionRequest","VerifierExecutionResult",
    "VerifierBoundaryEvidence","VerifierExecutionReport","build_verifier_execution_report",
    "VerifierFailureKind","VerifierFixtureKind","VerifierFixtureStatus","VerifierFixtureRisk",
    "VerifierFixture","VerifierFixtureResult","VerifierFixtureSuite","VerifierFixtureSuiteResult",
    "build_default_lean_fixture_suite","run_verifier_fixture_suite",
    "E2ETestDriveMode","E2ETestDriveStatus","E2EStepKind",
    "E2ETestDriveStep","E2ETestDriveReport","run_e2e_testdrive",
    "score_agent_experience",
    "score_alchemical_trace",
    "score_continuation_output",
    "score_curriculum",
    "score_curriculum_stage",
    "score_lawbook_assimilation_candidate",
    "score_object",
    "score_projection_candidate",
    "score_proof_digestion_trace",
    "score_repair_plan",
    "score_repair_loop",
    "score_route_telemetry_event",
    "score_verifier_feedback",
    "classify_flaw_from_message",
    "feedback_from_lean_adapter_trace",
    "feedback_from_proof_verification_result",
    "feedback_from_proof_verification_trace",
    "feedback_from_text",
    "feedback_from_verification_episode_trace",
    "make_repair_loop_trace_id",
    "make_repair_plan_id",
    "make_verifier_feedback_id",
    "plan_repair_from_feedback",
    "repair_loop_trace_to_agent_experiences",
    "repair_loop_trace_to_alchemical_trace",
    "repair_loop_trace_to_continuation_outputs",
    "repair_loop_trace_to_projection_candidates",
    "repair_loop_trace_to_route_telemetry_events",
    "run_repair_loop",
    "summarize_h_tilt_telemetry",
    "telemetry_events_from_episode",
    "transition_table",
    "run_verification_episode",
    "audit_m0_store",
    "make_server",
    "run_metabolic_cycle",
]

# SAIR v17 lawbook/replay integration
try:
    from .sair_v17_lawbook import (
        SairV17Lawbook,
        SairV17LawbookEntry,
        SairV17PackageManifest,
        load_sair_v17_lawbook,
    )
except Exception:
    pass

try:
    from .sair_v17_terminal_boundary import (
        TerminalBoundaryDecision,
        TerminalBoundaryVerdict,
        enforce_sair_v17_terminal_boundary,
        is_terminal_safe_status,
    )
except Exception:
    pass

try:
    from .sair_v17_constructors import (
        SairV17ConstructorCatalog,
        SairV17ConstructorRecommendation,
        load_sair_v17_constructor_catalog,
        recommend_sair_v17_constructors,
    )
except Exception:
    pass

try:
    from .sair_v17_replay_router import (
        SairV17ReplayRoute,
        SairV17ReplayRouter,
        build_sair_v17_replay_router,
    )
except Exception:
    pass

from mathgraph.mathlib_declaration_discovery import *
from mathgraph.proof_library_demo import *
from mathgraph.demo_release import *
from mathgraph.real_mathlib_demo import *
from mathgraph.lawbook_accumulator import *
from mathgraph.mathlib_digest import *
from mathgraph.reason_atlas import *
from mathgraph.constructor_atlas import *
from mathgraph.digest_scheduler import *
from mathgraph.digest_exports import *
from mathgraph.terminal_schema import (
    CanonicalTerminalForm,
    RefutationKind,
    VerifierBoundaryKind,
    can_promote_terminal_form,
    is_truth_promoting_boundary,
    refutation_kind_from_legacy,
    terminal_form_from_legacy,
)
from mathgraph.external_certificates import (
    ExternalBoundaryEvidence,
    ExternalCertificate,
    ExternalCertificateKind,
    ExternalCertificateImportDecision,
    ExternalCertificateStatus,
    ExternalVerifierKind,
    plan_external_certificate_import,
)
from mathgraph.closed_loop import (
    ClosedLoopStats,
    ClosedVerificationLoop,
    LoopEvent,
    LoopEventKind,
    PendingPair,
)
from mathgraph.route_priors import (
    SmoothedRoutePrior,
    SmoothedRoutePriorConfig,
    build_smoothed_route_prior,
    recommend_route_with_prior,
)
from mathgraph.causal_ir import (
    CausalClaim,
    CausalClaimKind,
    CausalEdge,
    CausalResolutionKind,
    CausalVariable,
    Intervention,
)
from mathgraph.grounding import (
    GroundingFunctionSpec,
    GroundingRecord,
    GroundingStatus,
    SensorSignature,
)
from mathgraph.signature_atlas import (
    SignatureAtlas,
    SignatureAtlasRecord,
    SignatureParseResult,
    SignatureRole,
    estimate_signature_features,
    normalize_signature,
    parse_check_output,
)
from mathgraph.contact_promotion import (
    ContactKind,
    ContactObstruction,
    ContactPromotionEngine,
    ContactSeed,
    ContactStatus,
    PromotedRouteLaw,
    PromotionDecision,
    PromotionPolicy,
    TransferTest,
)
from mathgraph.root_operator_schema import (
    ParameterSpec,
    RootOperatorEvaluationSummary,
    RootOperatorInstance,
    RootOperatorPromotionResult,
    RootOperatorSchema,
    compact_schema_name,
    make_root_operator_instance,
    make_root_operator_schema_id,
)
from mathgraph.root_operator_induction import (
    anti_unify_trace_group,
    induce_compositional_root_schemas,
    induce_root_operator_schemas,
    normalize_atom,
    normalize_trace_atoms,
)
from mathgraph.root_operator_promotion import (
    RootOperatorPromotionConfig,
    oracle_fraction_captured,
    promote_root_operator_schemas,
    residual_compression_metrics,
    root_operator_law_score,
    score_schema_on_tasks,
)
from mathgraph.reason_atlas_store import (
    ReasonAtlasEntry,
    ReasonAtlasEntryKind,
    ReasonAtlasEntryStatus,
    ReasonAtlasFeedbackEvent,
    ReasonAtlasFeedbackOutcome,
    ReasonAtlasQuery,
    ReasonAtlasStore,
    ReasonAtlasStoreConfig,
    ReasonAtlasTrust,
)
from mathgraph.schema_feedback import (
    apply_feedback_to_entry,
    compute_priority_score,
)
from mathgraph.reason_atlas_adapters import (
    entry_from_contact_promotion,
    entry_from_root_operator_schema,
)
from mathgraph.reason_atlas_feedback_loop import (
    ReasonAtlasFeedbackLoop,
    ReasonAtlasFeedbackLoopConfig,
)
from mathgraph.promotion_gate import (
    PromotionGate,
    PromotionGateConfig,
    PromotionGateDecision,
    PromotionGateDecisionKind,
    PromotionRejectionReason,
)
from mathgraph.closed_verification_loop import (
    ClosedVerificationLoop as PromotionClosedVerificationLoop,
    ClosedVerificationLoopConfig as PromotionClosedVerificationLoopConfig,
    ClosedVerificationLoopEvent as PromotionClosedVerificationLoopEvent,
    ClosedVerificationLoopResult as PromotionClosedVerificationLoopResult,
)
from mathgraph.finite_magma_world import (
    Equation,
    Term,
    check_finite_countermodel,
    eval_term,
    parse_equation,
    parse_term,
    table_satisfies_equation,
    table_violates_equation,
)
from mathgraph.breakthrough_loop import (
    BreakthroughAttempt,
    BreakthroughEpisodeResult,
    BreakthroughLoop,
    BreakthroughLoopConfig,
    BreakthroughTask,
)
from mathgraph.sair_task_loader import (
    LoadedSAIRTask,
    SAIRTaskLoadConfig,
    load_sair_equations,
    load_sair_matrix,
    make_sair_eval_sample,
    make_sair_false_tasks,
    normalize_sair_equation,
)
from mathgraph.sair_constructor_bank import (
    SAIRConstructor,
    attach_preferred_constructors,
    build_sair_constructor_bank,
    constructor_table_dict,
    preferred_constructors_for_task,
)
from mathgraph.sair_breakthrough_runner import (
    SAIRBreakthroughRunConfig,
    SAIRBreakthroughRunResult,
    run_sair_breakthrough_loop,
)
from mathgraph.sair_motif_hygiene import (
    SAIRMechanismAtom,
    SAIRCleanTrace,
    SAIRMotifHygieneConfig,
    SAIRMotifHygieneReport,
    clean_breakthrough_trace_rows,
    extract_clean_mechanism_atoms,
    filter_to_accepted_finite_countermodel_rows,
    normalize_constructor_name,
)
from mathgraph.sair_clean_motif_mining import (
    SAIRMotif,
    SAIRMotifMiningConfig,
    SAIRMotifMiningReport,
    deduplicate_subsumed_motifs,
    mine_clean_constructor_motifs,
    score_clean_motifs,
)
from mathgraph.sair_scheduler_evaluation import (
    SAIRSchedulerEvalConfig,
    SAIRSchedulerEvalReport,
    SAIRSchedulerPolicyResult,
    evaluate_scheduler_policies,
)
from mathgraph.sair_reason_atlas_admission import (
    SAIRReasonAtlasAdmissionConfig,
    SAIRReasonAtlasAdmissionReport,
    admit_clean_motifs_to_reason_atlas,
    admit_clean_schemas_to_reason_atlas,
    clean_motif_to_reason_atlas_entry,
    clean_root_schema_to_reason_atlas_entry,
    export_sair_reason_atlas_admission_report,
    load_sair_reason_atlas_priors,
)
from mathgraph.sair_scale_evaluation import (
    SAIRScaleEvalConfig,
    SAIRScaleEvalReport,
    compare_baseline_vs_reason_atlas,
    compute_attempt_efficiency_gain,
    compute_basin_coverage_gain,
    compute_compounding_gain,
    compute_repeatability_stats,
    compute_residual_compression_gain,
    run_sair_scale_evaluation,
)
from mathgraph.reason_atlas_htilt import (
    ReasonAtlasHTiltConfig,
    ReasonAtlasHTiltReport,
    ReasonAtlasHTiltScore,
    apply_htilt_scores_to_reason_atlas,
    estimate_htilt_for_reason_atlas,
    export_htilt_augmented_queue,
)
from mathgraph.sair_htilt_scale_evaluation import (
    SAIRHTiltScaleEvalConfig,
    SAIRHTiltScaleEvalReport,
    run_sair_htilt_scale_evaluation,
)
from mathgraph.viability_operators import (
    ViabilityOperatorConfig,
    ViabilityOperatorKind,
    ViabilityOperatorReport,
    ViabilityOperatorScore,
    rank_items_by_v,
    score_viability_operator,
)
from mathgraph.htilt_calibration import (
    HTiltCalibrationConfig,
    HTiltCalibrationReport,
    HTiltCalibrationResult,
    HTiltOperatorComparison,
    calibrate_htilt_operator,
    compare_htilt_operators,
    select_best_v_operator,
)
from mathgraph.sair_v_operator_evaluation import (
    SAIRVOperatorEvalConfig,
    SAIRVOperatorEvalReport,
    SAIRVOperatorPolicyResult,
    SAIRVOperatorSeedResult,
    evaluate_v_operators_multi_seed,
)
from mathgraph.lawbook_attention import (
    LawbookAttentionResult,
    LawbookAttentionTraceItem,
    retrieve_lawbook_attention,
)
from mathgraph.reason_coagulation import (
    CoagulatedReason,
    coagulate_reasons,
)
from mathgraph.decode_to_verify import (
    DecodeStatus,
    DecodeToVerifyResult,
    decode_reason_to_verify,
    decode_reasons_to_verify,
)
from mathgraph.compounding_metrics import (
    CompoundingMetrics,
    compute_compounding_metrics,
)
from mathgraph.compounding_lawbook_engine import (
    CompoundingLawbookEngineReport,
    run_compounding_lawbook_engine,
)
from mathgraph.sair_real_compounding_benchmark import (
    BenchmarkMode,
    BenchmarkResult,
    SAIRRealCompoundingBenchmarkReport,
    run_sair_real_compounding_benchmark,
)
from mathgraph.lawbook_admission import (
    AdmissionDecision,
    AdmissionEvidence,
    AdmissionLevel,
    ArtifactKind,
    LawbookAdmissionGate,
    LawbookAdmissionPolicy,
)
from mathgraph.lawbook_promotion import (
    promote_benchmark_outputs,
    promote_run_artifacts,
)
from mathgraph.multi_episode_compounding import (
    EpisodeConfig,
    EpisodeResult,
    MULTI_EPISODE_MODES,
    MultiEpisodeCompoundingResult,
    MultiEpisodeCompoundingRunner,
    MultiEpisodeConfig,
)
from mathgraph.real_sair_artifact_pack import (
    RealSairArtifactPackConfig,
    RealSairArtifactPackResult,
    RealSairArtifactPackRunner,
)
from mathgraph.invariants import (
    ClaimStatus,
    InvariantViolation,
    LawbookEntryInvariantReport,
    TerminalForm,
    TrustBoundaryEvidence,
    check_all_core_invariants,
    check_boundary_evidence_required,
    check_finite_failure_not_true,
    check_lawbook_entry_replayable,
    check_no_advisory_truth_promotion,
    check_provenance_preserved,
    check_terminal_form_contract,
    check_unsafe_artifact_rejected,
)
from mathgraph.evidence_manifest import EvidenceManifest, validate_evidence_manifest
from mathgraph.evidence_replay import EvidenceReplayResult, load_evidence_manifest, replay_evidence_manifest
from mathgraph.lawbook_acceptance import (
    LawbookAcceptanceResult,
    accept_lawbook_entry,
    check_lawbook_entry_replay_contract,
    lawbook_entry_from_evidence_manifest,
    reject_lawbook_entry,
    validate_lawbook_acceptance,
)
from mathgraph.semantic_validation import (
    FormalClaim,
    InformalClaim,
    SemanticValidationEvidence,
    SemanticValidationReport,
    SemanticValidationStatus,
    SemanticValidationViolation,
    TranslationAssumption,
    attach_semantic_validation_to_manifest,
    check_formal_verification_not_informal_solution,
    check_model_translation_not_truth,
    check_semantic_validation_required,
    semantic_validation_report,
    validate_claim_translation,
)
from mathgraph.reason_atlas import (
    ReasonAtlasEvidenceRef,
    ReasonAtlasMetricReport,
    ReasonAtlasPromotionStatus,
    ReasonAtlasTrustLevel,
    ReasonAtlasValidationReport,
    ReasonAtlasViolation,
    build_reason_atlas_entry_from_outcomes,
    check_reason_atlas_advisory_only,
    check_reason_atlas_evidence_refs,
    check_reason_atlas_no_truth_promotion,
    compute_reason_atlas_metrics,
    reason_atlas_report,
    summarize_constructor_family_performance,
    validate_reason_atlas_entry,
)
from mathgraph.compounding_engine import (
    CompoundingEngine,
    CompoundingEngineConfig,
    CompoundingEpisodeResult,
    CompoundingPolicyResult,
    CompoundingRunReport,
    run_compounding_loop,
)
from mathgraph.lawbook_schema import (
    BoundaryEvidenceType,
    LawbookAdmissionDecision as CanonicalLawbookAdmissionDecision,
    LawbookArtifact,
    LawbookQuery as CanonicalLawbookQuery,
    LawbookQueryResult as CanonicalLawbookQueryResult,
    ProvenanceType as CanonicalProvenanceType,
    TrustLevel as CanonicalTrustLevel,
)
from mathgraph.lawbook_boundary import (
    assert_advisory_cannot_promote,
    evaluate_lawbook_admission,
    explain_admission_decision,
    is_boundary_backed_terminal_candidate,
    normalize_terminal_form_value,
    reject_failed_search_as_truth,
)
from mathgraph.lawbook_ingest import (
    ingest_derived_closure_artifact,
    ingest_external_certificate,
    ingest_named_obstruction,
    ingest_promotion_gate_candidate,
    reject_advisory_artifact,
)
from mathgraph.lawbook_query import (
    query_attention_candidates,
    query_by_claim_id,
    query_by_domain,
    query_by_source_target,
    query_by_terminal_form,
    query_reusable_artifacts,
)
from mathgraph.lawbook_export import (
    artifact_hash,
    export_lawbook_jsonl,
    export_lawbook_manifest,
    export_lawbook_summary,
    replay_manifest_row,
)
from mathgraph.lawbook_reuse import (
    classify_reuse_kind,
    compute_action_change_rate,
    compute_lawbook_hit_rate,
    retrieve_reuse_candidates,
)
from mathgraph.verification_loop import (
    run_advisory_scheduled_episode,
    run_closed_verification_episode,
    run_compounding_episode,
    run_finite_countermodel_episode,
    run_recursive_residual_episode,
)
from mathgraph.recursive_residual_compounding import (
    CompactAtlasEvalResult,
    CompactAtlasRoute,
    ConstructorAttribution,
    ConstructorCandidate,
    RecursiveGenerationResult,
    RecursiveResidualCompoundingEngine,
    RecursiveResidualConfig,
    RecursiveResidualGateResult,
    RecursiveResidualRunReport,
    ResidualFrontierRow,
    TransferControlResult,
)
from mathgraph.etp_terms import (
    ETPEquation,
    ETPTerm,
    equation_features as etp_equation_features,
    parse_equation as parse_etp_equation,
    parse_term as parse_etp_term,
    safe_parse_equation as safe_parse_etp_equation,
    skeleton_signature,
    term_position_paths,
    variable_first_canonicalize_equation,
)
from mathgraph.quotient_state import BoundedTermUniverse, CongruenceClosure, UnionFind, closure_from_equation
from mathgraph.polarized_quotient_ir import (
    build_equation_features as build_pqir_equation_features,
    build_pair_features as build_pqir_pair_features,
    classify_basin as classify_pqir_basin,
    classify_deep_ir,
    recommend_constructor_families,
)
from mathgraph.constructor_families import (
    ConstructorFamily,
    all_constructor_families,
    default_priority_for_basin,
    normalize_family_name,
    parse_constructor_id,
)
from mathgraph.obstruction_atlas import ObstructionRecord, residual_queue, summarize_obstructions
from mathgraph.finite_magma import (
    FiniteCountermodelCertificate,
    FiniteMagma,
    equation_holds as finite_magma_equation_holds,
    equation_violated_with_witness,
    implication_false_certificate,
)
from mathgraph.magma_constructors import build_base_constructor_bank, build_random_constructor_bank, dedupe_constructors
from mathgraph.sat_cache import SatCache, build_sat_cache, compute_constructor_bandwidth, evaluate_route as evaluate_constructor_route
from mathgraph.policy_engine import ConstructorPolicy, build_policy_routes, build_residual_repair_policy
from mathgraph.proof_congruence import ExplainTrace, ProofCongruenceClosure, ProofStep, explain_bounded_congruence
from mathgraph.true_proof_templates import TrueProofTemplate, build_true_proof_template_inventory, classify_true_pair
from mathgraph.lean_artifacts import generate_false_countermodel_lean_skeleton, generate_true_congruence_lean_skeleton, write_lean_artifacts
from mathgraph.autonomous_finite_recovery import (
    FiniteRecoveryConfig,
    FiniteRecoveryResult,
    build_finite_recovery_core,
    evaluate_false_pairs as evaluate_autonomous_false_pairs,
    greedy_route as autonomous_greedy_route,
    pair_recovery_matrix as autonomous_pair_recovery_matrix,
    residual_marginal_repair as autonomous_residual_marginal_repair,
    route_metrics as autonomous_route_metrics,
)
from mathgraph.version import __version__, get_version_info
