namespace MathGraphPalomarClosure

/-!
# Closure-relative capability growth

This file is the complete statement surface for a finite witness extracted from
MathGraph's bounded closure experiments.  It uses only ordinary finite-state
notions: cyclic symmetry, one-site rewrites, and reflexive-transitive
reachability generated by two explicitly stated transition regimes.

The result separates four notions that are often conflated in adaptive search:
literal rewrite identity, identity modulo an already-available symmetry,
reachability under a retained regime, and raw constructor formability.
-/

/-- Tokens used by the finite witness. -/
inductive Token where
  | LT | LE | AND | OR | A | B | C | D
  deriving DecidableEq, Repr

/-- Four cyclic coordinates. -/
inductive Pos where
  | p0 | p1 | p2 | p3
  deriving DecidableEq, Repr

/-- One step of the old cyclic presentation symmetry. -/
def shift : Pos → Pos
  | .p0 => .p1
  | .p1 => .p2
  | .p2 => .p3
  | .p3 => .p0

/-- Iterated cyclic shift. -/
def shiftN : Nat → Pos → Pos
  | 0, p => p
  | n + 1, p => shiftN n (shift p)

/-- A literal one-site rewrite. -/
structure Rewrite where
  pos : Pos
  src : Token
  dst : Token
  deriving DecidableEq, Repr

/-- Two rewrites have the same closure-relative capability when the old cyclic
symmetry transports one coordinate to the other without changing source or
destination tokens. -/
def OrbitEq (r s : Rewrite) : Prop :=
  ∃ n : Nat, n < 4 ∧
    shiftN n r.pos = s.pos ∧
    r.src = s.src ∧
    r.dst = s.dst

def r0LTLE : Rewrite := ⟨.p0, .LT, .LE⟩
def r2LTLE : Rewrite := ⟨.p2, .LT, .LE⟩
def r3ANDOR : Rewrite := ⟨.p3, .AND, .OR⟩

/-- A finite state assigns one token to each coordinate. -/
abbrev State := Pos → Token

/-- Predecessor coordinate for cyclic state rotation. -/
def pred : Pos → Pos
  | .p0 => .p3
  | .p1 => .p0
  | .p2 => .p1
  | .p3 => .p2

/-- Old-language cyclic state transport. -/
def rotate (s : State) : State := fun p => s (pred p)

/-- Replace `src` by `dst` at one coordinate, acting as the identity when the
source token is absent there. -/
def replaceAt (p : Pos) (src dst : Token) (s : State) : State :=
  fun q =>
    if q = p then
      if s q = src then dst else s q
    else s q

/-- Regime 1: old cyclic transport together with the retained LT→LE capability
at any transported coordinate. -/
inductive Step1 : State → State → Prop where
  | rot (s : State) : Step1 s (rotate s)
  | ltle (s : State) (p : Pos) : Step1 s (replaceAt p .LT .LE s)

/-- Reachability under regime 1. -/
inductive Reach1 : State → State → Prop where
  | refl (s : State) : Reach1 s s
  | tail {x y z : State} : Reach1 x y → Step1 y z → Reach1 x z

/-- Regime 2 adjoins the AND→OR capability at any transported coordinate. -/
inductive Step2 : State → State → Prop where
  | rot (s : State) : Step2 s (rotate s)
  | ltle (s : State) (p : Pos) : Step2 s (replaceAt p .LT .LE s)
  | andor (s : State) (p : Pos) : Step2 s (replaceAt p .AND .OR s)

/-- Reachability under regime 2. -/
inductive Reach2 : State → State → Prop where
  | refl (s : State) : Reach2 s s
  | tail {x y z : State} : Reach2 x y → Step2 y z → Reach2 x z

/-- Source state for the second-generation reachability test. -/
def start : State
  | .p0 => .A
  | .p1 => .LT
  | .p2 => .B
  | .p3 => .AND

/-- Intermediate state after reuse of the retained LT→LE class. -/
def afterO1 : State
  | .p0 => .A
  | .p1 => .LE
  | .p2 => .B
  | .p3 => .AND

/-- Protected future target. -/
def target : State
  | .p0 => .A
  | .p1 => .LE
  | .p2 => .B
  | .p3 => .OR

/-- Raw one-site constructor formability, deliberately weaker than verified
reachability under a retained regime. -/
def RawFormable (r : Rewrite) : Prop :=
  ∃ p src dst, r = ⟨p, src, dst⟩

/-- Distinct literal LT→LE rewrites become one capability under the old cyclic
symmetry. -/
theorem orbit_identity : OrbitEq r0LTLE r2LTLE := by
  sorry

/-- The protected target is unreachable under cyclic transport plus the retained
LT→LE capability: no transition in regime 1 can create `OR`. -/
theorem strict_closure_obstruction : ¬ Reach1 start target := by
  sorry

/-- Adjoining the AND→OR capability strictly enlarges reachability: the target
is reachable in regime 2 by reusing LT→LE and then applying AND→OR. -/
theorem strict_closure_expansion : Reach2 start target := by
  sorry

/-- The later AND→OR capability was already formable in the raw one-site
constructor language.  Thus strict verified reachability growth here does not
amount to growth of raw syntax. -/
theorem raw_formability_boundary : RawFormable r3ANDOR := by
  sorry

end MathGraphPalomarClosure
