name = "MathGraphPalomarClosure"
version = "0.1.0"
defaultTargets = ["MathGraphPalomarClosure", "Challenge", "Solution"]

[[lean_lib]]
name = "MathGraphPalomarClosure"

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]
