#!/usr/bin/env python3
"""V54 continuous route-neutral capability-genesis census.

This is the bounded exact bridge between earlier capability-genesis witnesses
and a single continuously operating developer.

Frozen protocol
---------------
Worlds: every binary continuation table on 4 states x 3 continuations (4096).
Initial interface: continuation 0 only.
Initial executable archive: identity only.
Candidate operators: every deterministic map X -> X (4^4 = 256).
Candidate interface edits: add continuation 1 or 2.
Task selection: deterministic and route-neutral. For each world, before the
developer runs, select a five-task stream from exact properties of the frozen
world only:
  A: first nontrivial target already quotient-well-defined at B0.
  B: first target requiring exactly one additional continuation.
  C: first target requiring both additional continuations.
  D: second target requiring both additional continuations.
  E: first compositional future capability generated by A/B/C for which at
     least two acquired operators are exact ancestors.

A world enters the declared eligible census only when all five targets exist.
No route outcome or learned state is consulted by stream selection.

Developer
---------
For each task, the same stateful developer:
  1. tries retained capability closure;
  2. if the exact target is lawful on the current quotient, verifies and
     installs it as a reusable operator;
  3. otherwise emits the exact quotient-conflict residual and adds the
     lowest-cost continuation that strictly reduces that certified conflict;
  4. repeats until the target can be verifier-checked and installed.

The proposal mechanism never promotes truth. Verification is exhaustive over
all four states and quotient blocks.

Causal checks
-------------
A -> direct operator acquisition.
B -> one interface acquisition + operator acquisition.
C -> another interface acquisition + operator acquisition.
Restart -> state is serialized/reloaded.
E -> zero-acquisition compositional reuse.
Exact operator-ancestor ablation -> E disappears; restoration restores it.
D -> zero-new-interface future construction.
Exact probe ablation -> D becomes unavailable; restoration restores it.

This is a finite exhaustive calibration of repeated route-neutral capability
acquisition. It is not a claim of unrestricted natural-domain self-development.
"""

from __future__ import annotations

import hashlib
import itertools
import json
import os
from collections import Counter, defaultdict
from dataclasses import dataclass

X = tuple(range(4))
CONTINUATIONS = tuple(range(3))
IDENTITY = tuple(X)
ALL_FUNCTIONS = tuple(itertools.product(X, repeat=len(X)))


def all_tables():
    for bits in itertools.product((0, 1), repeat=len(X) * len(CONTINUATIONS)):
        yield tuple(
            tuple(bits[i * len(CONTINUATIONS):(i + 1) * len(CONTINUATIONS)])
            for i in X
        )


def classes(table, basis):
    buckets = defaultdict(list)
    for x in X:
        buckets[tuple(table[x][c] for c in basis)].append(x)
    return tuple(sorted(tuple(v) for v in buckets.values()))


def class_ids(cls):
    return {x: i for i, block in enumerate(cls) for x in block}


def congruent(table, basis, f):
    cls = classes(table, basis)
    ids = class_ids(cls)
    for block in cls:
        if len({ids[f[x]] for x in block}) != 1:
            return False
    return True


def conflict_pairs(table, basis, f):
    cls = classes(table, basis)
    ids = class_ids(cls)
    out = []
    for block in cls:
        for i in range(len(block)):
            for j in range(i + 1, len(block)):
                x, y = block[i], block[j]
                if ids[f[x]] != ids[f[y]]:
                    out.append((x, y))
    return tuple(out)


def min_extra_probes(table, f):
    for r in range(3):
        for extra in itertools.combinations((1, 2), r):
            basis = (0,) + extra
            if congruent(table, basis, f):
                return r, basis
    return None


def compose(f, g):
    """Return f after g."""
    return tuple(f[g[x]] for x in X)


def capability_closure(ops):
    seen = set(ops) | {IDENTITY}
    while True:
        current = tuple(seen)
        new = set()
        for f in current:
            for g in current:
                h = compose(f, g)
                if h not in seen:
                    new.add(h)
        if not new:
            return frozenset(seen)
        seen |= new


def nontrivial(f):
    return f != IDENTITY and len(set(f)) > 1


def frozen_stream(table):
    """Select the whole task stream before development, using world data only."""
    buckets = {0: [], 1: [], 2: []}
    for f in ALL_FUNCTIONS:
        if not nontrivial(f):
            continue
        depth = min_extra_probes(table, f)
        if depth is not None:
            buckets[depth[0]].append(f)
    for values in buckets.values():
        values.sort()

    if not (buckets[0] and buckets[1] and len(buckets[2]) >= 2):
        return None

    a = buckets[0][0]
    b = buckets[1][0]
    c = buckets[2][0]
    d = buckets[2][1]

    # E is a future capability already latent in the closure generated by A/B/C,
    # but causally dependent on at least two of those acquired operators.
    full = capability_closure((IDENTITY, a, b, c))
    for e in sorted(full):
        if e in {IDENTITY, a, b, c}:
            continue
        essential = []
        for removed in (a, b, c):
            reduced = [IDENTITY] + [op for op in (a, b, c) if op != removed]
            essential.append(e not in capability_closure(reduced))
        if sum(essential) >= 2:
            payload = {
                "A": a,
                "B": b,
                "C": c,
                "D": d,
                "E": e,
                "essential_ancestors": essential,
                "declared_depths": [0, 1, 2, 2, "composed"],
            }
            frozen = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
            payload["stream_sha256"] = hashlib.sha256(frozen).hexdigest()
            return payload
    return None


@dataclass
class Developer:
    table: tuple
    basis: tuple = (0,)
    ops: tuple = (IDENTITY,)

    def __post_init__(self):
        self.basis = tuple(self.basis)
        self.ops = list(dict.fromkeys(self.ops))
        self.events = []

    def valid_ops(self):
        return [op for op in self.ops if congruent(self.table, self.basis, op)]

    def closure(self):
        return capability_closure(self.valid_ops())

    def snapshot(self):
        payload = {
            "basis": list(self.basis),
            "ops": [list(op) for op in self.ops],
        }
        raw = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
        return payload, hashlib.sha256(raw).hexdigest()

    @classmethod
    def restart(cls, table, payload):
        return cls(
            table,
            tuple(payload["basis"]),
            tuple(tuple(op) for op in payload["ops"]),
        )

    def solve(self, target, allow_acquisition=True):
        if target in self.closure():
            self.events.append({"route": "REUSE", "basis": list(self.basis)})
            return "REUSE"

        if not allow_acquisition:
            self.events.append({"route": "UNKNOWN", "basis": list(self.basis)})
            return "UNKNOWN"

        # Exact operator verification: target behaviour on every state and
        # quotient congruence are checked independently of proposal order.
        if congruent(self.table, self.basis, target):
            assert tuple(target[x] for x in X) == tuple(target)
            self.ops.append(target)
            self.events.append(
                {"route": "EXPAND_OPERATOR", "basis": list(self.basis)}
            )
            return "EXPAND_OPERATOR"

        initial_conflicts = conflict_pairs(self.table, self.basis, target)
        assert initial_conflicts, "non-congruent target must expose a conflict"

        added = 0
        while not congruent(self.table, self.basis, target):
            current = len(conflict_pairs(self.table, self.basis, target))
            candidates = []
            for continuation in CONTINUATIONS:
                if continuation in self.basis:
                    continue
                next_basis = tuple(sorted(self.basis + (continuation,)))
                remaining = len(conflict_pairs(self.table, next_basis, target))
                if remaining < current:
                    candidates.append((remaining, continuation, next_basis))

            if not candidates:
                self.events.append(
                    {"route": "UNKNOWN_EXPRESSIVITY", "basis": list(self.basis)}
                )
                return "UNKNOWN_EXPRESSIVITY"

            # Frozen cost rule: minimal remaining certified conflict, then
            # lexical continuation id.
            candidates.sort()
            remaining, continuation, next_basis = candidates[0]
            self.basis = next_basis
            added += 1
            self.events.append(
                {
                    "route": "EXPAND_OBSERVATION",
                    "continuation": continuation,
                    "remaining_conflicts": remaining,
                    "basis": list(self.basis),
                }
            )

        assert congruent(self.table, self.basis, target)
        self.ops.append(target)
        self.events.append(
            {"route": "EXPAND_OPERATOR", "basis": list(self.basis)}
        )
        return f"EXPAND_OBSERVATION_{added}_THEN_OPERATOR"


summary = {
    "schema": "verified-developmental-navigation.continuous-capability-genesis.v54",
    "classification": "FINITE_EXHAUSTIVE_CAUSAL_CALIBRATION",
    "worlds_total": 0,
    "worlds_eligible": 0,
    "worlds_passed": 0,
    "worlds_failed": 0,
    "route_counts": Counter(),
    "stream_hashes": [],
    "first_witness": None,
    "gates": {
        "all_4096_worlds_enumerated": False,
        "route_neutral_stream_frozen_before_development": True,
        "single_continuous_developer": True,
        "direct_capability_acquisition_observed": False,
        "representation_expansion_observed_twice": False,
        "restart_replay_preserved_state": False,
        "future_compositional_capability_zero_acquisition": False,
        "ancestor_ablation_removed_future_capability": False,
        "ancestor_restoration_restored_future_capability": False,
        "future_task_required_no_new_interface": False,
        "probe_ablation_removed_future_capability": False,
        "probe_restoration_restored_future_capability": False,
        "wrong_promotions_zero": True,
        "all_eligible_worlds_pass": False,
    },
}

for world_id, table in enumerate(all_tables()):
    summary["worlds_total"] += 1
    task_stream = frozen_stream(table)
    if task_stream is None:
        continue

    summary["worlds_eligible"] += 1
    summary["stream_hashes"].append(task_stream["stream_sha256"])

    a = tuple(task_stream["A"])
    b = tuple(task_stream["B"])
    c = tuple(task_stream["C"])
    d = tuple(task_stream["D"])
    e = tuple(task_stream["E"])
    essential = list(task_stream["essential_ancestors"])

    dev = Developer(table)
    route_a = dev.solve(a)
    route_b = dev.solve(b)
    route_c = dev.solve(c)

    # Freeze and restart before the two future tasks.
    snapshot, snapshot_hash = dev.snapshot()
    restarted = Developer.restart(table, snapshot)
    replay_snapshot, replay_hash = restarted.snapshot()

    # E is a genuinely new future requested capability, but should already be
    # executable from retained A/B/C composition without acquisition.
    route_e = restarted.solve(e)

    ok = True
    ok &= route_a == "EXPAND_OPERATOR"
    ok &= route_b == "EXPAND_OBSERVATION_1_THEN_OPERATOR"
    ok &= route_c == "EXPAND_OBSERVATION_1_THEN_OPERATOR"
    ok &= snapshot_hash == replay_hash
    ok &= route_e == "REUSE"

    # Exact ancestor ablations at the pre-D state.
    essential_removed = 0
    essential_restored = 0
    for removed, is_essential in zip((a, b, c), essential):
        if not is_essential:
            continue
        ablated_ops = [IDENTITY] + [op for op in restarted.ops if op != removed]
        ablated = Developer(table, restarted.basis, tuple(ablated_ops))
        if ablated.solve(e, allow_acquisition=False) == "UNKNOWN":
            essential_removed += 1
        else:
            ok = False

        restored = Developer(table, restarted.basis, tuple(restarted.ops))
        if restored.solve(e, allow_acquisition=False) == "REUSE":
            essential_restored += 1
        else:
            ok = False

    ok &= essential_removed >= 2
    ok &= essential_restored == essential_removed

    # D was frozen from the beginning and required both future probes from B0.
    # After A/B/C development it should need no new interface development.
    basis_before_d = restarted.basis
    route_d = restarted.solve(d)
    ok &= route_d == "EXPAND_OPERATOR"
    ok &= restarted.basis == basis_before_d

    # Removing either acquired continuation invalidates D under the coarser
    # quotient. Acquisition is disabled in the ablation arm.
    probe_failures = 0
    for probe in (1, 2):
        ablated_basis = tuple(x for x in restarted.basis if x != probe)
        ablated = Developer(table, ablated_basis, tuple(restarted.ops))
        if ablated.solve(d, allow_acquisition=False) == "UNKNOWN":
            probe_failures += 1
        else:
            ok = False

    restored = Developer(table, restarted.basis, tuple(restarted.ops))
    probe_restored = restored.solve(d, allow_acquisition=False) == "REUSE"
    ok &= probe_failures == 2
    ok &= probe_restored

    routes = [route_a, route_b, route_c, route_e, route_d]
    summary["route_counts"].update(routes)

    if ok:
        summary["worlds_passed"] += 1
    else:
        summary["worlds_failed"] += 1

    if summary["first_witness"] is None:
        summary["first_witness"] = {
            "world_id": world_id,
            "table": table,
            "stream": task_stream,
            "routes": routes,
            "final_basis": list(restarted.basis),
            "snapshot_sha256": snapshot_hash,
            "essential_ancestor_ablations_passed": essential_removed,
            "probe_ablations_passed": probe_failures,
            "passed": bool(ok),
        }

g = summary["gates"]
g["all_4096_worlds_enumerated"] = summary["worlds_total"] == 4096
g["direct_capability_acquisition_observed"] = summary["route_counts"]["EXPAND_OPERATOR"] > 0
g["representation_expansion_observed_twice"] = (
    summary["route_counts"]["EXPAND_OBSERVATION_1_THEN_OPERATOR"]
    >= 2 * summary["worlds_eligible"]
)
g["restart_replay_preserved_state"] = summary["worlds_passed"] > 0
g["future_compositional_capability_zero_acquisition"] = (
    summary["route_counts"]["REUSE"] >= summary["worlds_eligible"]
)
g["ancestor_ablation_removed_future_capability"] = summary["worlds_passed"] > 0
g["ancestor_restoration_restored_future_capability"] = summary["worlds_passed"] > 0
g["future_task_required_no_new_interface"] = summary["worlds_passed"] > 0
g["probe_ablation_removed_future_capability"] = summary["worlds_passed"] > 0
g["probe_restoration_restored_future_capability"] = summary["worlds_passed"] > 0
g["all_eligible_worlds_pass"] = (
    summary["worlds_eligible"] > 0
    and summary["worlds_passed"] == summary["worlds_eligible"]
    and summary["worlds_failed"] == 0
)

summary["route_counts"] = dict(summary["route_counts"])
stream_digest = hashlib.sha256(
    "\n".join(sorted(summary["stream_hashes"])).encode()
).hexdigest()
summary["eligible_stream_set_sha256"] = stream_digest
summary.pop("stream_hashes")

summary["all_v54_gates_pass"] = all(g.values())
summary["verdict"] = (
    "PASS_CONTINUOUS_ROUTE_NEUTRAL_CAPABILITY_GENESIS_V54"
    if summary["all_v54_gates_pass"]
    else "FAIL_CONTINUOUS_ROUTE_NEUTRAL_CAPABILITY_GENESIS_V54"
)
summary["claim_boundary"] = (
    "PASS means that, exhaustively over the frozen 4-state/3-continuation binary universe, "
    "every world satisfying the route-neutral predeclared eligibility rule supports one continuous "
    "developer that repeatedly acquires verified executable capability, changes representation only "
    "after exact quotient conflicts, survives restart, exhibits zero-acquisition future composition, "
    "and loses/restores future capability under exact ancestor and probe ablations. "
    "This is a bounded finite causal calibration, not natural-domain or unrestricted open-ended self-development."
)

out = (
    "verified-developmental-navigation/case_studies/finite_inevitability/"
    "results_v54_continuous_capability_genesis/result.json"
)
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as handle:
    json.dump(summary, handle, indent=2, sort_keys=True)

print(json.dumps(summary, indent=2, sort_keys=True))

if not summary["all_v54_gates_pass"]:
    raise SystemExit("V54 frozen verdict failed")
