import MathGraph.Calculus.SymmetryBreakingAnchor

namespace MathGraph.Calculus

/-- A minimal abstract symmetry sufficient to expose the orientation boundary:
a renaming whose square is the identity.  No group library is required. -/
structure InvolutiveSymmetry (Ω : Type) where
  rename : Ω → Ω
  involutive : ∀ x, rename (rename x) = x

/-- The symmetry acts freely when no carrier point is fixed. -/
def InvolutiveSymmetry.FixedPointFree {Ω : Type}
    (S : InvolutiveSymmetry Ω) : Prop :=
  ∀ x, S.rename x ≠ x

/-- The two-point orbit generated by an anchor under an involution. -/
def InvolutiveSymmetry.InOrbit {Ω : Type}
    (S : InvolutiveSymmetry Ω) (a y : Ω) : Prop :=
  y = a ∨ y = S.rename a

/-- A single externally distinguished orbit point generates an ordered task;
its partner is obtained from symmetry rather than supplied independently. -/
def InvolutiveSymmetry.taskFromAnchor {Ω : Type}
    (S : InvolutiveSymmetry Ω) (a : Ω) : Stage26TaskBoundary Ω :=
  ⟨a, S.rename a⟩

/-- Renaming the chosen anchor moves the source to the old target. -/
theorem involutive_anchor_flip_source
    {Ω : Type} (S : InvolutiveSymmetry Ω) (a : Ω) :
    (S.taskFromAnchor (S.rename a)).source =
      (S.taskFromAnchor a).target := by
  rfl

/-- By involutivity, renaming the chosen anchor moves the target to the old
source.  Thus one orbit representative determines orientation and changing the
representative reverses it. -/
theorem involutive_anchor_flip_target
    {Ω : Type} (S : InvolutiveSymmetry Ω) (a : Ω) :
    (S.taskFromAnchor (S.rename a)).target =
      (S.taskFromAnchor a).source := by
  exact S.involutive a

/-- Under a free involution the anchor and its partner are genuinely distinct,
so the orbit contains a real symmetry ambiguity rather than a degenerate fixed
point. -/
theorem free_involution_anchor_partner_distinct
    {Ω : Type} (S : InvolutiveSymmetry Ω)
    (hfree : S.FixedPointFree) (a : Ω) :
    S.rename a ≠ a :=
  hfree a

/-- An endogenous canonical anchor would have to be invariant under every
symmetry of the seed.  For the present one-symmetry abstraction this means it
must be a fixed point. -/
structure InvolutiveSymmetry.CanonicalAnchor {Ω : Type}
    (S : InvolutiveSymmetry Ω) where
  anchor : Ω
  invariant : S.rename anchor = anchor

/-- General orbit/stabilizer obstruction: a free symmetry action has no
symmetry-respecting canonical orbit representative.  Any operational choice of
one point from such an orbit therefore carries exogenous symmetry-breaking
information. -/
theorem no_canonical_anchor_of_free_involution
    {Ω : Type} (S : InvolutiveSymmetry Ω)
    (hfree : S.FixedPointFree) :
    ¬ Nonempty S.CanonicalAnchor := by
  intro h
  rcases h with ⟨a⟩
  exact hfree a.anchor a.invariant

/-- A direct stabilizer formulation of the same boundary. -/
def InvolutiveSymmetry.Stabilizes {Ω : Type}
    (S : InvolutiveSymmetry Ω) (a : Ω) : Prop :=
  S.rename a = a

/-- Free action means the nontrivial involution stabilizes no possible anchor. -/
theorem free_involution_has_no_stabilized_anchor
    {Ω : Type} (S : InvolutiveSymmetry Ω)
    (hfree : S.FixedPointFree) :
    ¬ ∃ a, S.Stabilizes a := by
  intro h
  rcases h with ⟨a, ha⟩
  exact hfree a ha

/-- Bool negation is the concrete Stage-29 witness of the general theorem. -/
def BoolNotSymmetry : InvolutiveSymmetry Bool where
  rename := Bool.not
  involutive := by
    intro b
    cases b <;> rfl

/-- Bool negation acts freely. -/
theorem bool_not_symmetry_fixed_point_free :
    BoolNotSymmetry.FixedPointFree := by
  intro b
  cases b <;> simp [BoolNotSymmetry]

/-- The generic anchor-generated task specializes exactly to Stage 29. -/
theorem bool_orbit_task_recovers_stage29 (a : Bool) :
    BoolNotSymmetry.taskFromAnchor a = Stage29TaskFromAnchor a := by
  rfl

/-- The earlier finite impossibility theorem is now an instance of the generic
free-orbit law. -/
theorem bool_no_canonical_anchor_from_orbit_law :
    ¬ Nonempty BoolNotSymmetry.CanonicalAnchor := by
  exact no_canonical_anchor_of_free_involution
    BoolNotSymmetry bool_not_symmetry_fixed_point_free

/-- Generalized symmetry-boundary certificate.

Relative to any seed with a fixed-point-free involutive renaming, an external
ordered source-target pair is not primitive: one chosen orbit representative
is sufficient because symmetry generates its partner, and choosing the other
representative reverses the task.  But no equivariant endogenous selector of a
representative exists, because equivariance would require a fixed point and a
free orbit has none.  Stage 29 is exactly the Bool instance. -/
theorem orbit_stabilizer_boundary_certificate :
    (∀ a : Bool,
      BoolNotSymmetry.taskFromAnchor a = Stage29TaskFromAnchor a) ∧
    BoolNotSymmetry.FixedPointFree ∧
    (¬ Nonempty BoolNotSymmetry.CanonicalAnchor) ∧
    (¬ ∃ a : Bool, BoolNotSymmetry.Stabilizes a) ∧
    ((BoolNotSymmetry.taskFromAnchor (BoolNotSymmetry.rename false)).source =
      (BoolNotSymmetry.taskFromAnchor false).target) ∧
    ((BoolNotSymmetry.taskFromAnchor (BoolNotSymmetry.rename false)).target =
      (BoolNotSymmetry.taskFromAnchor false).source) := by
  refine ⟨bool_orbit_task_recovers_stage29,
    bool_not_symmetry_fixed_point_free,
    bool_no_canonical_anchor_from_orbit_law, ?_, ?_, ?_⟩
  · exact free_involution_has_no_stabilized_anchor
      BoolNotSymmetry bool_not_symmetry_fixed_point_free
  · exact involutive_anchor_flip_source BoolNotSymmetry false
  · exact involutive_anchor_flip_target BoolNotSymmetry false

end MathGraph.Calculus
