import MathGraph.Calculus.BareTransportAlgebra

universe u v

namespace MathGraph.Calculus

/-- Free finite continuation generated by completely raw directed witness data.
The generator supplies no identity, composition, symmetry, equality, or laws. -/
inductive FreePath {Ω : Type u} (G : Ω → Ω → Type v) : Ω → Ω → Type (max u v) where
  | nil {x : Ω} : FreePath G x x
  | step {x y z : Ω} : G x y → FreePath G y z → FreePath G x z

/-- Finite continuation composes by structural recursion. Composition is not
assumed in the raw generator. -/
def FreePath.append {Ω : Type u} {G : Ω → Ω → Type v}
    {x y z : Ω} : FreePath G x y → FreePath G y z → FreePath G x z
  | .nil, q => q
  | .step e p, q => .step e (FreePath.append p q)

/-- A raw generator becomes a one-step continuation. -/
def FreePath.ofGenerator {Ω : Type u} {G : Ω → Ω → Type v}
    {x y : Ω} : G x y → FreePath G x y :=
  fun e => .step e .nil

/-- The free-path closure of raw directed data is already a bare transport
algebra. Identity comes from the empty continuation; composition comes from
path concatenation. -/
def rawPathAlgebra (Ω : Type u) (G : Ω → Ω → Type v) :
    BareTransportAlgebra where
  Obj := Ω
  Hom := FreePath G
  ident := fun _ => .nil
  comp := fun p q => FreePath.append p q

/-- Mutual identity data is therefore derivable from raw generators without
putting identity or composition into the generator itself. -/
def rawMutualRefl {Ω : Type u} (G : Ω → Ω → Type v) (x : Ω) :
    Mutual (FreePath G) x x :=
  bareMutualRefl (rawPathAlgebra Ω G) x

/-- The raw generator can be totally empty and reflexive continuation still
exists: staying put is the zero-length path, not a supplied generator edge. -/
def emptyGenerator {Ω : Type u} : Ω → Ω → Type :=
  fun _ _ => Empty

def emptyGenerator_refl {Ω : Type u} (x : Ω) :
    FreePath (emptyGenerator (Ω := Ω)) x x :=
  .nil

/-- Small nontrivial raw world. There is only one primitive directed event. -/
def oneEdgeGenerator : Bool → Bool → Type :=
  fun x y => match x, y with
    | false, true => Unit
    | _, _ => Empty

/-- The single primitive event generates nontrivial continuation. -/
def oneEdge_false_to_true : FreePath oneEdgeGenerator false true :=
  FreePath.ofGenerator ()

/-- Reverse continuation is not manufactured by free closure. Thus symmetry is
still not primitive or automatic. -/
def oneEdge_no_reverse : FreePath oneEdgeGenerator true false → Empty := by
  intro p
  cases p with
  | step e rest => exact nomatch e

/-- With no primitive generators at all, free closure cannot create a
nontrivial change of Bool state. -/
def emptyGenerator_no_false_to_true :
    FreePath (emptyGenerator (Ω := Bool)) false true → Empty := by
  intro p
  cases p with
  | step e rest => exact nomatch e

/-- Decisive genesis certificate: identity and composition are generated by
finite path closure from raw directed possibility, while nontrivial change
requires at least one primitive directed generator and reverse change is not
silently added. -/
def raw_transport_genesis_certificate :
    FreePath (emptyGenerator (Ω := Bool)) false false ×
    (FreePath (emptyGenerator (Ω := Bool)) false true → Empty) ×
    FreePath oneEdgeGenerator false true ×
    (FreePath oneEdgeGenerator true false → Empty) :=
  ⟨.nil,
   emptyGenerator_no_false_to_true,
   oneEdge_false_to_true,
   oneEdge_no_reverse⟩

end MathGraph.Calculus
