import MathGraph.Calculus.ReconstructionStage4Separation
import MathGraph.Calculus.Refinement

universe u v w

namespace MathGraph.Calculus

/-- Even the empty raw generator refines pointwise into any richer generator:
there is no primitive evidence to translate. -/
def emptyGenerator_refines_twoWay :
    GeneratorRefines (emptyGenerator (Ω := Bool)) twoWayGenerator :=
  fun _ _ e => nomatch e

/-- With no cross-endpoint generators, `false` and `true` are separated by the
source probe `false`: it reaches itself by the zero path but cannot reach
`true`. -/
def emptyGenerator_false_true_separated :
    BedrockSeparated (emptyGenerator (Ω := Bool)) false true := by
  refine ⟨false, ?_⟩
  intro hEq
  have hReach : Nonempty (FreePath (emptyGenerator (Ω := Bool)) false true) :=
    Eq.mp hEq ⟨(.nil : FreePath (emptyGenerator (Ω := Bool)) false false)⟩
  rcases hReach with ⟨p⟩
  exact emptyGenerator_no_false_to_true p

/-- In the two-way generator world the same endpoints have generated identity,
so their reflected reachability consequences are equal. -/
def twoWay_false_true_consequentialEq :
    ConsequentialEq (IncomingReachabilityLanguage twoWayGenerator) false true :=
  generatedIdentity_to_consequentialEq twoWay_generatedIdentity

/-- Decisive obstruction: raw-generator refinement does *not* generally induce
the old semantic information refinement. Adding directed possibilities may
coarsen reachability observations by making previously separated endpoints
mutually reachable. -/
theorem generatorRefinement_not_semanticRefinement :
    GeneratorRefines (emptyGenerator (Ω := Bool)) twoWayGenerator ×
    ¬ Refines
        (IncomingReachabilityLanguage twoWayGenerator)
        (IncomingReachabilityLanguage (emptyGenerator (Ω := Bool))) := by
  constructor
  · exact emptyGenerator_refines_twoWay
  · intro hRef
    have hEmptyEq :
        ConsequentialEq
          (IncomingReachabilityLanguage (emptyGenerator (Ω := Bool)))
          false true :=
      hRef twoWay_false_true_consequentialEq
    exact
      ((consequentialEq_iff_not_separated
        (IncomingReachabilityLanguage (emptyGenerator (Ω := Bool)))
        false true).mp hEmptyEq)
        emptyGenerator_false_true_separated

/-- A probe family selects which boundary positions are allowed to test an
endpoint by incoming reachability. This is the first explicitly selected
observation interface on the ascent. -/
def ProbeFamily (ι : Type w) (Ω : Type u) := ι → Ω

/-- Reachability consequences generated by a selected family of source probes. -/
def ProbedReachabilityLanguage {ι : Type w} {Ω : Type u}
    (G : Ω → Ω → Type v) (P : ProbeFamily ι Ω) : Language ι Ω Prop :=
  fun i x => Nonempty (FreePath G (P i) x)

/-- Add one new probe without changing the raw transition world. -/
def extendProbe {ι : Type w} {Ω : Type u}
    (P : ProbeFamily ι Ω) (k : Ω) : ProbeFamily (Sum ι Unit) Ω
  | .inl i => P i
  | .inr _ => k

/-- Probe extension is definitionally the original language-extension
operation applied to the reachability observation generated by the new probe. -/
theorem probedLanguage_extendProbe_eq_extend
    {ι : Type w} {Ω : Type u}
    (G : Ω → Ω → Type v) (P : ProbeFamily ι Ω) (k : Ω) :
    ProbedReachabilityLanguage G (extendProbe P k) =
      extend (ProbedReachabilityLanguage G P)
        (fun x => Nonempty (FreePath G k x)) :=
  rfl

/-- Therefore adding a probe, unlike adding a transition, is guaranteed to
refine semantic identity. The old information-refinement law is reconstructed
as monotonicity of *observation selection*, not monotonicity of world dynamics. -/
theorem extendProbe_refines
    {ι : Type w} {Ω : Type u}
    (G : Ω → Ω → Type v) (P : ProbeFamily ι Ω) (k : Ω) :
    Refines
      (ProbedReachabilityLanguage G (extendProbe P k))
      (ProbedReachabilityLanguage G P) := by
  rw [probedLanguage_extendProbe_eq_extend]
  exact extend_refines
    (ProbedReachabilityLanguage G P)
    (fun x => Nonempty (FreePath G k x))

/-- Stage-5 certificate: the ascent separates two notions that were conflated
if one tried to identify raw-world enrichment with information refinement.
Transition enrichment is non-monotone observationally; probe enrichment is the
operation that reconstructs the verified refinement algebra. -/
theorem reconstruction_stage5_certificate
    {ι : Type w} {Ω : Type u}
    (G : Ω → Ω → Type v) (P : ProbeFamily ι Ω) (k : Ω) :
    Refines
      (ProbedReachabilityLanguage G (extendProbe P k))
      (ProbedReachabilityLanguage G P) :=
  extendProbe_refines G P k

end MathGraph.Calculus
