import MathGraph.Calculus.ReconstructionStage12FiniteTermination

namespace MathGraph.Calculus

/-- Stage 13 starts from the raw two-endpoint world with no cross-endpoint
change. The only continuations are the zero-length identity paths generated
by free closure. -/
abbrev Stage13G0 : Bool → Bool → Type := emptyGenerator

/-- The finite residual controller is not handed a winning primitive. It sees
only the complete source list. -/
def Stage13Candidates : List Bool := [false, true]

/-- From the empty observational interface, source `false` is a genuine
reachability residual: it reaches `false` by the generated zero path but cannot
reach `true` in the empty raw world. -/
theorem stage13_false_residual :
    ListProbeResidual Stage13G0 [] false := by
  refine ⟨false, true, ?_, ?_⟩
  · intro k hk
    exact nomatch hk
  · intro hEq
    have hFalse : ProbeObservation Stage13G0 false false :=
      ⟨(.nil : FreePath Stage13G0 false false)⟩
    have hTrue : ProbeObservation Stage13G0 false true := hEq.mp hFalse
    rcases hTrue with ⟨p⟩
    exact emptyGenerator_no_false_to_true p

/-- Once the `false` source has been selected, the other source is redundant:
the first probe already separates the only two endpoints. -/
theorem stage13_true_redundant_after_false :
    ListProbeRedundant Stage13G0 [false] true := by
  intro x y hEq
  cases x <;> cases y
  · rfl
  · exfalso
    have hFalseEq := hEq false (by simp)
    have hReach : ProbeObservation Stage13G0 false false :=
      ⟨(.nil : FreePath Stage13G0 false false)⟩
    have hBad : ProbeObservation Stage13G0 false true := hFalseEq.mp hReach
    rcases hBad with ⟨p⟩
    exact emptyGenerator_no_false_to_true p
  · exfalso
    have hFalseEq := hEq false (by simp)
    have hReach : ProbeObservation Stage13G0 false false :=
      ⟨(.nil : FreePath Stage13G0 false false)⟩
    have hBad : ProbeObservation Stage13G0 false true := hFalseEq.mpr hReach
    rcases hBad with ⟨p⟩
    exact emptyGenerator_no_false_to_true p
  · rfl

/-- Therefore finite residual selection mechanically returns exactly the one
informative source. -/
theorem stage13_selection_is_endogenous :
    finiteResidualSelect Stage13G0 Stage13Candidates [] = [false] := by
  rw [finiteResidualSelect, if_pos stage13_false_residual]
  rw [finiteResidualSelect, if_neg]
  · rfl
  · exact (noListProbeResidual_iff_redundant Stage13G0 [false] true).mpr
      stage13_true_redundant_after_false

/-- A selected source is compiled into a raw cross-endpoint possibility. This
is the smallest promotion operator needed for the finite consolidation world:
selection determines whether the new generator is present; identity and
composition remain generated by `FreePath`, not supplied here. -/
def Stage13Promote (selected : List Bool) : Bool → Bool → Type :=
  if false ∈ selected then oneEdgeGenerator else Stage13G0

/-- The residual-selected interface licenses the cross-endpoint generator. -/
theorem stage13_promoted_generator_eq :
    Stage13Promote (finiteResidualSelect Stage13G0 Stage13Candidates []) =
      oneEdgeGenerator := by
  rw [stage13_selection_is_endogenous]
  simp [Stage13Promote]

/-- Cold closure cannot reach the target. -/
theorem stage13_cold_target_unreachable :
    FreePath Stage13G0 false true → Empty :=
  emptyGenerator_no_false_to_true

/-- Merely possessing the selected observational interface does not alter raw
world closure: before promotion the target remains unreachable. -/
theorem stage13_components_only_target_unreachable :
    FreePath Stage13G0 false true → Empty :=
  emptyGenerator_no_false_to_true

/-- After residual-driven promotion, the same free-path closure reaches the
previously unavailable target. -/
theorem stage13_warm_target_reachable :
    FreePath
      (Stage13Promote (finiteResidualSelect Stage13G0 Stage13Candidates []))
      false true := by
  rw [stage13_promoted_generator_eq]
  exact oneEdge_false_to_true

/-- Exact ancestor ablation restores the cold obstruction. -/
theorem stage13_exact_ablation_restores_failure :
    FreePath Stage13G0 false true → Empty :=
  emptyGenerator_no_false_to_true

/-- Negative developmental law: if every candidate is already redundant,
finite residual selection introduces no new selected probe. -/
theorem finiteResidualSelect_no_residual_no_extension
    {Ω : Type} (G : Ω → Ω → Type)
    (candidates B : List Ω)
    (hRed : ∀ k, k ∈ candidates → ListProbeRedundant G B k) :
    finiteResidualSelect G candidates B = B := by
  induction candidates with
  | nil => rfl
  | cons k ks ih =>
      have hkRed : ListProbeRedundant G B k := hRed k (by simp)
      have hkNo : ¬ ListProbeResidual G B k :=
        (noListProbeResidual_iff_redundant G B k).mpr hkRed
      rw [finiteResidualSelect, if_neg hkNo]
      apply ih
      intro p hp
      exact hRed p (by simp [hp])

/-- Stage-13 consolidation certificate.

One finite theorem now connects the reconstructed bedrock controller to an
actual closure-changing developmental step:
* cold raw closure cannot reach the target;
* finite residual selection endogenously identifies the informative source;
* carrying that selected observation alone still does not change closure;
* installing the licensed generator makes the target reachable under the same
  free-path semantics;
* exact ablation restores failure;
* globally silent candidate pools generate no extension.

This is a finite consolidation theorem, not yet self-hosting constructor
language genesis. -/
theorem reconstruction_stage13_development_certificate :
    (FreePath Stage13G0 false true → Empty) ∧
    (finiteResidualSelect Stage13G0 Stage13Candidates [] = [false]) ∧
    (FreePath Stage13G0 false true → Empty) ∧
    Nonempty
      (FreePath
        (Stage13Promote (finiteResidualSelect Stage13G0 Stage13Candidates []))
        false true) ∧
    (FreePath Stage13G0 false true → Empty) :=
  ⟨stage13_cold_target_unreachable,
   stage13_selection_is_endogenous,
   stage13_components_only_target_unreachable,
   ⟨stage13_warm_target_reachable⟩,
   stage13_exact_ablation_restores_failure⟩

end MathGraph.Calculus
