import MathGraph.Calculus.ReconstructionStage11MinimalSufficient

universe u v

namespace MathGraph.Calculus

/-- Consequential equality generated by a finite list of source probes. This
list form lets us state and verify a terminating residual-selection procedure
without assuming a pre-existing fixed probe-index type. -/
def ListProbeEq {Ω : Type u}
    (G : Ω → Ω → Type v) (B : List Ω) (x y : Ω) : Prop :=
  ∀ k : Ω, k ∈ B → ProbeObservation G k x = ProbeObservation G k y

/-- A candidate source probe has a residual when the current finite interface
aliases some pair that the candidate separates. -/
def ListProbeResidual {Ω : Type u}
    (G : Ω → Ω → Type v) (B : List Ω) (k : Ω) : Prop :=
  ∃ x y : Ω,
    ListProbeEq G B x y ∧
    ProbeObservation G k x ≠ ProbeObservation G k y

/-- A candidate is redundant when it is constant on every current
observational equivalence class. -/
def ListProbeRedundant {Ω : Type u}
    (G : Ω → Ω → Type v) (B : List Ω) (k : Ω) : Prop :=
  ∀ x y : Ω,
    ListProbeEq G B x y →
    ProbeObservation G k x = ProbeObservation G k y

/-- Absence of a residual is exactly redundancy, with excluded middle exposed
only at equality of the Prop-valued probe outcomes. -/
theorem noListProbeResidual_iff_redundant
    {Ω : Type u} (G : Ω → Ω → Type v) (B : List Ω) (k : Ω) :
    (¬ ListProbeResidual G B k) ↔ ListProbeRedundant G B k := by
  constructor
  · intro hNo x y hEq
    exact Classical.em (ProbeObservation G k x = ProbeObservation G k y) |>.elim
      (fun hSame => hSame)
      (fun hNe => False.elim (hNo ⟨x, y, hEq, hNe⟩))
  · intro hRed hResidual
    rcases hResidual with ⟨x, y, hEq, hNe⟩
    exact hNe (hRed x y hEq)

/-- More selected probes can only refine list consequential equality. -/
theorem listProbeEq_mono
    {Ω : Type u} {G : Ω → Ω → Type v}
    {B C : List Ω} (hsub : ∀ k, k ∈ B → k ∈ C)
    {x y : Ω} :
    ListProbeEq G C x y → ListProbeEq G B x y := by
  intro hEq k hk
  exact hEq k (hsub k hk)

/-- Once a probe is redundant, adding further probes cannot make it
non-redundant. -/
theorem listProbeRedundant_mono
    {Ω : Type u} {G : Ω → Ω → Type v}
    {B C : List Ω} {k : Ω}
    (hRed : ListProbeRedundant G B k)
    (hsub : ∀ p, p ∈ B → p ∈ C) :
    ListProbeRedundant G C k := by
  intro x y hEq
  exact hRed x y (listProbeEq_mono hsub hEq)

/-- Every probe already present in a finite interface is redundant relative to
that interface. -/
theorem member_listProbeRedundant
    {Ω : Type u} {G : Ω → Ω → Type v}
    {B : List Ω} {k : Ω} (hk : k ∈ B) :
    ListProbeRedundant G B k := by
  intro x y hEq
  exact hEq k hk

/-- Residual selection is logically classical: deciding whether an arbitrary
Prop-valued residual exists is exactly the explicit choice boundary needed by
the finite controller. The generated interface and all later certificates
remain ordinary propositions once this decision is made. -/
local instance residualPropDecidable (p : Prop) : Decidable p :=
  Classical.propDecidable p

/-- One finite residual-selection pass. A candidate is added exactly when it
currently has a residual; otherwise it is forgotten. The recursion is purely
on the finite candidate list, so termination is structural rather than an
assumption. -/
noncomputable def finiteResidualSelect {Ω : Type u}
    (G : Ω → Ω → Type v) : List Ω → List Ω → List Ω
  | [], B => B
  | k :: ks, B =>
      if ListProbeResidual G B k then
        finiteResidualSelect G ks (k :: B)
      else
        finiteResidualSelect G ks B

/-- Residual selection never deletes an already selected probe. -/
theorem finiteResidualSelect_contains_base
    {Ω : Type u} (G : Ω → Ω → Type v) :
    ∀ candidates B p,
      p ∈ B → p ∈ finiteResidualSelect G candidates B := by
  intro candidates
  induction candidates with
  | nil =>
      intro B p hp
      exact hp
  | cons k ks ih =>
      intro B p hp
      by_cases h : ListProbeResidual G B k
      · rw [finiteResidualSelect, if_pos h]
        exact ih (k :: B) p (by simp [hp])
      · rw [finiteResidualSelect, if_neg h]
        exact ih B p hp

/-- Every candidate processed by the finite controller is redundant relative
to the final selected interface: selected candidates are redundant because
present; forgotten candidates remain redundant under later refinement. -/
theorem finiteResidualSelect_processed_redundant
    {Ω : Type u} (G : Ω → Ω → Type v) :
    ∀ candidates B k,
      k ∈ candidates →
      ListProbeRedundant G (finiteResidualSelect G candidates B) k := by
  intro candidates
  induction candidates with
  | nil =>
      intro B k hk
      exact nomatch hk
  | cons a rest ih =>
      intro B k hk
      have hkCases : k = a ∨ k ∈ rest := by
        simpa [eq_comm] using hk
      by_cases hResidual : ListProbeResidual G B a
      · rw [finiteResidualSelect, if_pos hResidual]
        rcases hkCases with hka | hkrest
        · subst k
          apply member_listProbeRedundant
          exact finiteResidualSelect_contains_base G rest (a :: B) a (by simp)
        · exact ih (a :: B) k hkrest
      · rw [finiteResidualSelect, if_neg hResidual]
        rcases hkCases with hka | hkrest
        · subst k
          have hRedB : ListProbeRedundant G B a :=
            (noListProbeResidual_iff_redundant G B a).mp hResidual
          apply listProbeRedundant_mono hRedB
          intro p hp
          exact finiteResidualSelect_contains_base G rest B p hp
        · exact ih B k hkrest

/-- If `allProbes` enumerates every possible source, one structurally finite
selection pass ends in a saturated interface. -/
theorem finiteResidualSelect_saturated
    {Ω : Type u} (G : Ω → Ω → Type v)
    (allProbes : List Ω)
    (hcomplete : ∀ k : Ω, k ∈ allProbes)
    (B0 : List Ω) :
    ∀ k : Ω,
      ListProbeRedundant G (finiteResidualSelect G allProbes B0) k := by
  intro k
  exact finiteResidualSelect_processed_redundant G allProbes B0 k (hcomplete k)

/-- Full all-source consequential equality in direct list form. -/
def FullReachabilityEq {Ω : Type u}
    (G : Ω → Ω → Type v) (x y : Ω) : Prop :=
  ∀ k : Ω, ProbeObservation G k x = ProbeObservation G k y

/-- The saturated finite result is sufficient for the full all-source
reachability quotient. -/
theorem finiteResidualSelect_sufficient
    {Ω : Type u} (G : Ω → Ω → Type v)
    (allProbes : List Ω)
    (hcomplete : ∀ k : Ω, k ∈ allProbes)
    (B0 : List Ω) (x y : Ω) :
    ListProbeEq G (finiteResidualSelect G allProbes B0) x y ↔
      FullReachabilityEq G x y := by
  constructor
  · intro hSelected k
    exact (finiteResidualSelect_saturated G allProbes hcomplete B0 k) x y hSelected
  · intro hFull k _
    exact hFull k

/-- Stage-12 certificate: on an explicitly enumerated finite source universe,
the bedrock residual controller terminates by structural recursion and its
output is saturated and sufficient for the full reachability identity. This
bridges the generated-probe story to finite-basis results without assuming the
minimal basis itself as input. -/
theorem reconstruction_stage12_finite_termination_certificate
    {Ω : Type u} (G : Ω → Ω → Type v)
    (allProbes : List Ω)
    (hcomplete : ∀ k : Ω, k ∈ allProbes)
    (B0 : List Ω) :
    (∀ k : Ω,
      ListProbeRedundant G (finiteResidualSelect G allProbes B0) k) ∧
    (∀ x y : Ω,
      ListProbeEq G (finiteResidualSelect G allProbes B0) x y ↔
        FullReachabilityEq G x y) :=
  ⟨finiteResidualSelect_saturated G allProbes hcomplete B0,
   finiteResidualSelect_sufficient G allProbes hcomplete B0⟩

end MathGraph.Calculus
