namespace VerifiedDevelopmentalNavigation
namespace CapabilityCalculus

universe u v

/-- A capability world exposes live guarded choices and their possible
adversarial/nondeterministic outcomes. -/
structure World (X : Type u) (C : Type v) where
  live : C → Prop
  applicable : C → X → Prop
  outcome : C → X → X → Prop

namespace World

variable {X : Type u} {C : Type v} (W : World X C)

/-- One-step controllable predecessor: there exists a live applicable
capability whose every possible outcome lies in K. -/
def Pre (K : X → Prop) (x : X) : Prop :=
  ∃ c : C, W.live c ∧ W.applicable c x ∧
    ∀ y : X, W.outcome c x y → K y

/-- Least goal-closure generated by protected goals and controllable
predecessors. This is the logical form of forced finite progress. -/
inductive ForcesGoal (Goal Bad : X → Prop) : X → Prop
  | goal {x : X} : Goal x → ForcesGoal Goal Bad x
  | step {x : X} (c : C) :
      ¬ Bad x →
      W.live c →
      W.applicable c x →
      (∀ y : X, W.outcome c x y → ForcesGoal Goal Bad y) →
      ForcesGoal Goal Bad x

/-- A predicate is closed under goals and live controllable predecessors. -/
def GoalClosed (Goal Bad K : X → Prop) : Prop :=
  (∀ x : X, Goal x → K x) ∧
  ∀ (x : X) (c : C),
    ¬ Bad x →
    W.live c →
    W.applicable c x →
    (∀ y : X, W.outcome c x y → K y) →
    K x

/-- The forced-goal predicate is the least goal/predecessor-closed predicate. -/
theorem forcesGoal_least
    {Goal Bad K : X → Prop}
    (hK : W.GoalClosed Goal Bad K)
    {x : X}
    (h : W.ForcesGoal Goal Bad x) :
    K x := by
  induction h with
  | goal hg =>
      exact hK.1 _ hg
  | step c hnotbad hlive happ hnext ih =>
      exact hK.2 _ c hnotbad hlive happ (by
        intro y hy
        exact ih y hy)

/-- A nonterminal forced-goal proof exposes a concrete live capability whose
every outcome is itself forced-goal. -/
theorem forcesGoal_progress
    {Goal Bad : X → Prop} {x : X}
    (h : W.ForcesGoal Goal Bad x)
    (hnot : ¬ Goal x) :
    ∃ c : C, ¬ Bad x ∧ W.live c ∧ W.applicable c x ∧
      ∀ y : X, W.outcome c x y → W.ForcesGoal Goal Bad y := by
  cases h with
  | goal hg =>
      exact False.elim (hnot hg)
  | step c hnotbad hlive happ hnext =>
      exact ⟨c, hnotbad, hlive, happ, hnext⟩

/-- A safety invariant excludes Bad and is closed under at least one live
capability at every nonterminal member. -/
def SafeInvariant
    (Bad SafeTerminal K : X → Prop) : Prop :=
  ∀ x : X, K x →
    ¬ Bad x ∧
    (SafeTerminal x ∨ W.Pre K x)

/-- Greatest-safety semantics as the union of all safe invariants. -/
def Viable
    (Bad SafeTerminal : X → Prop)
    (x : X) : Prop :=
  ∃ K : X → Prop, K x ∧ W.SafeInvariant Bad SafeTerminal K

/-- Every established safety invariant embeds into Viable. -/
theorem safeInvariant_subset_viable
    {Bad SafeTerminal K : X → Prop}
    (hK : W.SafeInvariant Bad SafeTerminal K)
    {x : X}
    (hx : K x) :
    W.Viable Bad SafeTerminal x := by
  exact ⟨K, hx, hK⟩

/-- Viable itself is a safety invariant, hence is the greatest such
post-fixed region. -/
theorem viable_is_safeInvariant
    {Bad SafeTerminal : X → Prop} :
    W.SafeInvariant Bad SafeTerminal (W.Viable Bad SafeTerminal) := by
  intro x hx
  rcases hx with ⟨K, hxK, hK⟩
  have h := hK x hxK
  refine ⟨h.1, ?_⟩
  cases h.2 with
  | inl hterminal =>
      exact Or.inl hterminal
  | inr hpre =>
      rcases hpre with ⟨c, hlive, happ, hout⟩
      exact Or.inr ⟨c, hlive, happ, by
        intro y hy
        exact ⟨K, hout y hy, hK⟩⟩

/-- Greatest-property theorem for safety: every safe invariant is contained in
Viable. -/
theorem viable_greatest
    {Bad SafeTerminal K : X → Prop}
    (hK : W.SafeInvariant Bad SafeTerminal K) :
    ∀ ⦃x : X⦄, K x → W.Viable Bad SafeTerminal x := by
  intro x hx
  exact W.safeInvariant_subset_viable hK hx

/-- Every viable nonterminal state exposes a live capability whose every
outcome remains viable. This is the safety/draw arbitration witness. -/
theorem viable_continuation
    {Bad SafeTerminal : X → Prop} {x : X}
    (hx : W.Viable Bad SafeTerminal x)
    (hnot : ¬ SafeTerminal x) :
    ∃ c : C, W.live c ∧ W.applicable c x ∧
      ∀ y : X, W.outcome c x y → W.Viable Bad SafeTerminal y := by
  have h := W.viable_is_safeInvariant x hx
  cases h.2 with
  | inl hterminal =>
      exact False.elim (hnot hterminal)
  | inr hpre =>
      exact hpre

end World
end CapabilityCalculus
end VerifiedDevelopmentalNavigation
